'use strict';
// Code-drawn pictures for the Grades 1–5 lesson page (primary.js). Every picture here is SVG built
// from the lesson's own words and numbers: a clock drawn at the lesson's time, the letters the
// lesson blends, the story's own scenes. Nothing is generated by an image model, so a lesson costs
// nothing to draw and a picture can never show a time or a word the lesson does not say.
//
// The style is a children's picture book: bright toy colours, round friendly shapes, faces with
// rosy cheeks, a smiling sun. Teaching marks stay exact — the hour hand is short and thick, the
// minute hand long and thin, and each points where the lesson's time puts it.
const C = {
  navy: '#303749', green: '#298157', mint: '#DEF4E7', teal: '#0F6A73', blue: '#2E5E90', amber: '#F2A20C',
  cream: '#FFF8E8', purple: '#584A93', slate: '#5B6472', ink: '#2D3436', white: '#FFFFFF',
  // toy colours
  coral: '#FF6B6B', coralD: '#E04F4F', orange: '#FF9F43', yellow: '#FECA57', lime: '#7BD389', grassC: '#4CC37A',
  sky: '#54A0FF', skyD: '#2E86DE', violet: '#A55EEA', pink: '#FF8FB1', aqua: '#1DD1A1', brown: '#A0673E',
};
// one colour per letter block, in turn
const TILE = ['#FF6B6B', '#54A0FF', '#FF9F43', '#1DD1A1', '#A55EEA', '#FF8FB1'];
const SKIN = '#E0A97E'; const SKIN2 = '#C98C5E'; const HAIR = '#2B2521';

const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const svg = (w, h, body, label, vb) => `<svg class="qart" viewBox="${vb || `0 0 ${w} ${h}`}" role="img"${label ? ` aria-label="${esc(label)}"` : ''} xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
const FONT = "font-family=\"Inter,'Noto Nastaliq Urdu',sans-serif\"";
const r1 = (v) => Math.round(v * 10) / 10;

// "9:00" → {h:9, m:0}
function parseTime(t) {
  const m = /^\s*(\d{1,2})\s*[:.]\s*(\d{2})\s*$/.exec(String(t || ''));
  if (!m) throw new Error(`clock: cannot read the time "${t}"`);
  const h = Number(m[1]); const min = Number(m[2]);
  if (h < 0 || h > 23 || min > 59) throw new Error(`clock: "${t}" is not a time`);
  return { h, m: min };
}

// ── CLOCKS ────────────────────────────────────────────────────────────────────────────────
// An analogue clock at the lesson's time. The hour hand is short and thick (navy), the minute hand
// long and thin (orange), as the lessons describe them; both hands are drawn first from the centre,
// then their arrow tips. style: 'alarm' (bells and feet, a child's alarm clock), 'wall' (a wooden
// wall clock), 'mini' (a small badge with 12, 3, 6, 9).
const NUM_DOTS = ['#FFE3E3', '#E3F0FF', '#FFF1D6', '#DDF7EC', '#EFE3FF', '#FFE6F0'];
function clockFace(cx, cy, r, time, { style = 'alarm', rim = C.coral } = {}) {
  const { h, m } = parseTime(time);
  const pt = (deg, rr) => [cx + rr * Math.sin((deg * Math.PI) / 180), cy - rr * Math.cos((deg * Math.PI) / 180)];
  let s = '';
  if (style === 'alarm') {
    // two bells and a hammer on top, two feet below
    for (const side of [-1, 1]) {
      const [bx, by] = pt(side * 40, r * 1.1);
      s += `<g transform="translate(${r1(bx)} ${r1(by)}) rotate(${side * 40})"><path d="M${-r * 0.27} ${r * 0.07}a${r * 0.27} ${r * 0.27} 0 0 1 ${r * 0.54} 0z" fill="${C.yellow}" stroke="${C.orange}" stroke-width="${r1(r * 0.035)}"/>`
        + `<rect x="${r1(-r * 0.3)}" y="${r1(r * 0.04)}" width="${r1(r * 0.6)}" height="${r1(r * 0.08)}" rx="${r1(r * 0.04)}" fill="${C.orange}"/></g>`;
      const [fx, fy] = pt(180 - side * 38, r * 0.98);
      s += `<line x1="${r1(fx)}" y1="${r1(fy)}" x2="${r1(fx + side * r * 0.14)}" y2="${r1(fy + r * 0.2)}" stroke="${C.coralD}" stroke-width="${r1(r * 0.11)}" stroke-linecap="round"/>`;
    }
    s += `<line x1="${cx}" y1="${r1(cy - r * 1.02)}" x2="${cx}" y2="${r1(cy - r * 1.14)}" stroke="${C.orange}" stroke-width="${r1(r * 0.06)}" stroke-linecap="round"/><circle cx="${cx}" cy="${r1(cy - r * 1.17)}" r="${r1(r * 0.06)}" fill="${C.yellow}" stroke="${C.orange}" stroke-width="${r1(r * 0.025)}"/>`;
  }
  const ring = style === 'wall' ? C.brown : rim;
  s += `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${ring}"/>`
    + `<circle cx="${r1(cx - r * 0.18)}" cy="${r1(cy - r * 0.2)}" r="${r1(r * 0.9)}" fill="#fff" opacity=".18"/>`
    + `<circle cx="${cx}" cy="${cy}" r="${r1(r * 0.86)}" fill="#fff"/>`
    + `<circle cx="${cx}" cy="${cy}" r="${r1(r * 0.8)}" fill="none" stroke="${style === 'wall' ? '#F1E3D3' : '#FFE3E3'}" stroke-width="${r1(r * 0.03)}"/>`;
  for (let i = 0; i < 60; i++) {
    if (i % 5 === 0) continue;
    const [x, y] = pt(i * 6, r * 0.76);
    s += `<circle cx="${r1(x)}" cy="${r1(y)}" r="${r1(r * 0.014)}" fill="#B2BAC6"/>`;
  }
  const nums = style === 'mini' ? [12, 3, 6, 9] : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
  for (const n of nums) {
    const [x, y] = pt(n * 30, r * (style === 'mini' ? 0.6 : 0.62));
    if (style !== 'mini') s += `<circle cx="${r1(x)}" cy="${r1(y)}" r="${r1(r * 0.135)}" fill="${NUM_DOTS[n % NUM_DOTS.length]}"/>`;
    s += `<text x="${r1(x)}" y="${r1(y + r * 0.075)}" text-anchor="middle" ${FONT} font-weight="800" font-size="${r1(r * (style === 'mini' ? 0.26 : 0.2))}" fill="${C.ink}">${n}</text>`;
  }
  const hourDeg = ((h % 12) + m / 60) * 30; const minDeg = m * 6;
  const [hx, hy] = pt(hourDeg, r * 0.45); const [mx, my] = pt(minDeg, r * 0.76);
  s += `<line x1="${cx}" y1="${cy}" x2="${r1(hx)}" y2="${r1(hy)}" stroke="${C.navy}" stroke-width="${r1(r * 0.1)}" stroke-linecap="round"/>`;
  s += `<line x1="${cx}" y1="${cy}" x2="${r1(mx)}" y2="${r1(my)}" stroke="${C.orange}" stroke-width="${r1(r * 0.045)}" stroke-linecap="round"/>`;
  // arrow tips on both hands
  const tip = (deg, rr, w, col) => {
    const [x0, y0] = pt(deg, rr); const [xl, yl] = pt(deg - w, rr * 0.86); const [xr, yr] = pt(deg + w, rr * 0.86);
    return `<path d="M${r1(x0)} ${r1(y0)}L${r1(xl)} ${r1(yl)}L${r1(xr)} ${r1(yr)}z" fill="${col}" stroke="${col}" stroke-width="${r1(r * 0.02)}" stroke-linejoin="round"/>`;
  };
  s += tip(hourDeg, r * 0.5, 13, C.navy) + tip(minDeg, r * 0.8, 6, C.orange);
  s += `<circle cx="${cx}" cy="${cy}" r="${r1(r * 0.085)}" fill="${C.yellow}" stroke="${C.navy}" stroke-width="${r1(r * 0.03)}"/>`;
  return s;
}
// a cheerful digital clock: a blue body on little feet, two buttons, a dark screen with bright digits
function digitalClock(x, y, w, h, text, { label } = {}) {
  let s = `<rect x="${x + w * 0.16}" y="${y + h - 4}" width="${w * 0.12}" height="${h * 0.16}" rx="4" fill="${C.skyD}"/><rect x="${x + w * 0.72}" y="${y + h - 4}" width="${w * 0.12}" height="${h * 0.16}" rx="4" fill="${C.skyD}"/>`
    + `<rect x="${x + w * 0.2}" y="${y - h * 0.12}" width="${w * 0.14}" height="${h * 0.16}" rx="4" fill="${C.coral}"/><rect x="${x + w * 0.4}" y="${y - h * 0.1}" width="${w * 0.1}" height="${h * 0.14}" rx="4" fill="${C.yellow}"/>`
    + `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${h * 0.22}" fill="${C.sky}"/>`
    + `<rect x="${x}" y="${y + h * 0.62}" width="${w}" height="${h * 0.38}" rx="${h * 0.2}" fill="${C.skyD}" opacity=".45"/>`
    + `<rect x="${x + w * 0.07}" y="${y + h * 0.14}" width="${w * 0.86}" height="${h * 0.64}" rx="${h * 0.12}" fill="#1E272E"/>`
    + `<text x="${x + w / 2}" y="${y + h * 0.63}" text-anchor="middle" ${FONT} font-weight="800" font-size="${r1(h * 0.5)}" fill="#7CFFB2" letter-spacing="2">${esc(text)}</text>`;
  if (label) {
    const parts = String(label).split('|').map((p) => p.trim());
    const ly = y + h + h * 0.16 + 22;
    if (parts.length === 2) {
      s += `<path d="M${x + w * 0.1} ${ly - 18}q0 6 6 6h${w * 0.3 - 12}q6 0 6 -6" fill="none" stroke="${C.coral}" stroke-width="3" stroke-linecap="round"/>`
        + `<path d="M${x + w * 0.56} ${ly - 18}q0 6 6 6h${w * 0.3 - 12}q6 0 6 -6" fill="none" stroke="${C.aqua}" stroke-width="3" stroke-linecap="round"/>`
        + `<text x="${x + w * 0.27}" y="${ly + 6}" text-anchor="middle" ${FONT} font-weight="800" font-size="16" fill="${C.coralD}">${esc(parts[0])}</text>`
        + `<text x="${x + w * 0.73}" y="${ly + 6}" text-anchor="middle" ${FONT} font-weight="800" font-size="16" fill="#0E9F7E">${esc(parts[1])}</text>`;
    } else s += `<text x="${x + w / 2}" y="${ly + 6}" text-anchor="middle" ${FONT} font-weight="800" font-size="16" fill="${C.slate}">${esc(label)}</text>`;
  }
  return s;
}
const sparkle = (x, y, k = 1, col = C.yellow) => `<path transform="translate(${x} ${y}) scale(${k})" d="M0 -10C1.5 -3 3 -1.5 10 0C3 1.5 1.5 3 0 10C-1.5 3 -3 1.5 -10 0C-3 -1.5 -1.5 -3 0 -10z" fill="${col}"/>`;
function clock(spec) {
  return svg(200, 204, clockFace(100, 100, 84, spec.time), `clock showing ${spec.time}`, '0 -2 200 204');
}
function clockPair(spec) {
  const legend = spec.hour_label || spec.minute_label;
  const H = legend ? 272 : 226;
  let s = clockFace(104, 112, 86, spec.time)
    + `<circle cx="238" cy="118" r="21" fill="${C.mint}"/><text x="238" y="131" text-anchor="middle" ${FONT} font-weight="800" font-size="36" fill="${C.green}">=</text>`
    + digitalClock(270, 74, 200, 92, spec.digital || spec.time, { label: spec.digital_label })
    + sparkle(262, 40, 0.9) + sparkle(462, 54, 0.7, C.pink) + sparkle(30, 30, 0.7, C.sky);
  if (legend) {
    const y = 250;
    if (spec.hour_label) s += `<rect x="6" y="${y - 16}" width="226" height="30" rx="15" fill="#EEF1F7"/><line x1="20" y1="${y - 1}" x2="48" y2="${y - 1}" stroke="${C.navy}" stroke-width="9" stroke-linecap="round"/><text x="58" y="${y + 4}" ${FONT} font-weight="700" font-size="15" fill="${C.ink}">${esc(spec.hour_label)}</text>`;
    if (spec.minute_label) s += `<rect x="242" y="${y - 16}" width="232" height="30" rx="15" fill="#FFF1E2"/><line x1="256" y1="${y - 1}" x2="292" y2="${y - 1}" stroke="${C.orange}" stroke-width="4.5" stroke-linecap="round"/><text x="302" y="${y + 4}" ${FONT} font-weight="700" font-size="15" fill="${C.ink}">${esc(spec.minute_label)}</text>`;
  }
  return svg(480, H, s, `analogue clock and digital clock both showing ${spec.digital || spec.time}`);
}

// ── LETTERS AND SOUNDS ────────────────────────────────────────────────────────────────────
// a letter block, like a toy: a bright face, a shine on top, a darker edge below
function tile(x, y, w, h, text, color, fs) {
  x = r1(x); y = r1(y); w = r1(w);
  const rad = Math.min(12, h * 0.26);
  return `<rect x="${x}" y="${y + 5}" width="${w}" height="${h}" rx="${rad}" fill="#000" opacity=".16"/>`
    + `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${rad}" fill="${color}"/>`
    + `<rect x="${r1(x + 4)}" y="${y + 3}" width="${r1(w - 8)}" height="${r1(h * 0.34)}" rx="${r1(rad * 0.7)}" fill="#fff" opacity=".28"/>`
    + `<text x="${r1(x + w / 2)}" y="${r1(y + h * 0.7)}" text-anchor="middle" ${FONT} font-weight="800" font-size="${fs}" fill="#fff">${esc(text)}</text>`;
}
const tileW = (t, fs) => Math.max(fs * 1.6, String(t).length * fs * 0.62 + fs * 1.0);
// a row of blocks; returns {s, w}
function tileRow(parts, x, y, h, fs, gap = 8) {
  let s = ''; let cx = x;
  parts.forEach((p, i) => { const w = tileW(p, fs); s += tile(cx, y, w, h, p, TILE[i % TILE.length], fs); cx += w + gap; });
  return { s, w: cx - gap - x };
}
function tiles(spec) {
  const { s, w } = tileRow(spec.parts, 4, 4, 46, 24);
  return svg(Math.ceil(w + 8), 60, s, `letter tiles ${spec.parts.join(' ')}`);
}
// the word blender: the sounds drop into a smiling blender and come out as one word
function blender(spec) {
  const { parts, word } = spec;
  let s = '';
  const fs = 22; const ws = parts.map((p) => tileW(p, fs)); const total = ws.reduce((a, b) => a + b, 0) + 10 * (parts.length - 1);
  let x = 128 - total / 2;
  parts.forEach((p, i) => {
    const y = 4 + (i % 2) * 12;
    s += `<path d="M${r1(x + ws[i] / 2)} ${y + 50}v10" stroke="${TILE[i % TILE.length]}" stroke-width="3" stroke-linecap="round" stroke-dasharray="2 5" opacity=".7"/>`;
    s += tile(x, y, ws[i], 40, p, TILE[i % TILE.length], fs); x += ws[i] + 10;
  });
  // the jar with a happy face, the lid, the base with its button
  s += '<path d="M76 80h104l-12 92H88z" fill="#D9F2FF" stroke="#54A0FF" stroke-width="4" stroke-linejoin="round"/>'
    + '<path d="M92 104c10 8 24 8 36 0s26-8 36 0M94 128c10 8 22 8 34 0s24-8 34 0" fill="none" stroke="#A55EEA" stroke-width="3" stroke-linecap="round" opacity=".55"/>'
    + '<circle cx="114" cy="140" r="4" fill="#2D3436"/><circle cx="142" cy="140" r="4" fill="#2D3436"/><path d="M118 152c6 6 14 6 20 0" stroke="#2D3436" stroke-width="3" fill="none" stroke-linecap="round"/>'
    + '<ellipse cx="106" cy="150" rx="6" ry="3.5" fill="#FF8FB1" opacity=".7"/><ellipse cx="150" cy="150" rx="6" ry="3.5" fill="#FF8FB1" opacity=".7"/>'
    + '<rect x="70" y="68" width="116" height="16" rx="8" fill="#54A0FF"/><rect x="118" y="60" width="20" height="10" rx="4" fill="#2E86DE"/>'
    + '<path d="M84 172h88l8 30H76z" fill="#2E5E90"/><circle cx="128" cy="188" r="8" fill="#FECA57" stroke="#fff" stroke-width="2"/>';
  // motion lines, an arrow out, the word in a starry bubble
  s += '<path d="M60 110l-12-4M58 130h-14M60 150l-12 4M196 110l12-4M198 130h14" stroke="#B2BAC6" stroke-width="3" stroke-linecap="round"/>';
  s += `<path d="M214 130h52" stroke="${C.green}" stroke-width="7" stroke-linecap="round"/><path d="M260 112l22 18-22 18z" fill="${C.green}"/>`;
  const wfs = 34; const ww = Math.max(150, String(word).length * wfs * 0.62 + 46);
  s += `<rect x="296" y="98" width="${r1(ww)}" height="64" rx="32" fill="${C.green}"/><rect x="304" y="102" width="${r1(ww - 16)}" height="20" rx="10" fill="#fff" opacity=".18"/>`
    + `<text x="${r1(296 + ww / 2)}" y="142" text-anchor="middle" ${FONT} font-weight="800" font-size="${wfs}" fill="#fff">${esc(word)}</text>`
    + sparkle(300, 88, 1, C.yellow) + sparkle(r1(286 + ww), 172, 0.8, C.pink) + sparkle(r1(300 + ww * 0.6), 80, 0.6, C.sky);
  return svg(Math.max(480, Math.ceil(310 + ww)), 210, s, `word blender: ${parts.join(' + ')} makes ${word}`);
}
// the board's word blender: each word's sounds as blocks, an arrow, and a line to write the word on
function blenderList(spec) {
  const rows = spec.words; const h = 40; const gap = 14; const fs = 20;
  let s = '';
  rows.forEach((parts, r) => {
    const y = r * (h + gap) + 4;
    s += `<rect x="0" y="${y - 4}" width="480" height="${h + 10}" rx="12" fill="${r % 2 ? '#F4F7FC' : '#FFF8EC'}"/>`;
    const { s: t, w } = tileRow(parts, 8, y, h - 4, fs, 6);
    s += t;
    const ax = Math.max(230, w + 26);
    s += `<path d="M${ax} ${y + h / 2}h30" stroke="${TILE[r % TILE.length]}" stroke-width="5" stroke-linecap="round"/><path d="M${ax + 28} ${y + h / 2 - 9}l13 9-13 9z" fill="${TILE[r % TILE.length]}"/>`
      + `<line x1="${ax + 54}" y1="${y + h - 6}" x2="${ax + 196}" y2="${y + h - 6}" stroke="${C.navy}" stroke-width="3" stroke-dasharray="2 7" stroke-linecap="round"/>`
      + `<g transform="translate(${ax + 204} ${y + h - 30}) rotate(35)"><rect x="0" y="0" width="7" height="24" rx="2" fill="${C.yellow}"/><path d="M0 24l3.5 7 3.5-7z" fill="#F1C27D"/><rect x="0" y="-4" width="7" height="5" rx="2" fill="${C.pink}"/></g>`;
  });
  return svg(480, rows.length * (h + gap) + 6, s, `word blender: ${rows.map((p) => p.join('-')).join(', ')}`);
}
// blending step by step as a staircase: s + u = su, su + nn = sun, sun + y = sunny, a star at the top.
// The steps are the lesson's own ("'su' + 'nn' = 'sun'": a double letter is one sound), so they come
// from the lesson, never from joining the letters.
function blendSteps(spec) {
  const steps = spec.steps; const n = steps.length;
  const stepH = 58; const H = n * stepH + 6; const fs = 19;
  let s = '';
  const stairColors = ['#DDF7EC', '#E3F0FF', '#FFF1D6', '#EFE3FF', '#FFE3E3'];
  // the stairs first, so no step covers the words on the one below it
  steps.forEach((_, k) => { s += `<rect x="${k * 70}" y="${H - (k + 1) * stepH}" width="${480 - k * 70}" height="${stepH}" rx="12" fill="${stairColors[k % stairColors.length]}"/>`; });
  steps.forEach(([a, b, out], k) => {
    const top = H - (k + 1) * stepH; const x0 = k * 70;
    const y = top + 10; const wa = tileW(a, fs); const wb = tileW(b, fs);
    let cx = x0 + 10;
    s += tile(cx, y, wa, 36, a, '#8E99AB', fs); cx += wa + 6;
    s += `<text x="${r1(cx + 9)}" y="${y + 26}" text-anchor="middle" ${FONT} font-weight="800" font-size="22" fill="${C.slate}">+</text>`; cx += 20;
    s += tile(cx, y, wb, 36, b, TILE[(k + 1) % TILE.length], fs); cx += wb + 6;
    s += `<text x="${r1(cx + 9)}" y="${y + 26}" text-anchor="middle" ${FONT} font-weight="800" font-size="22" fill="${C.slate}">=</text>`; cx += 20;
    const last = k === n - 1; const wo = tileW(out, fs) + (last ? 14 : 0);
    s += `<rect x="${r1(cx)}" y="${y}" width="${r1(wo)}" height="36" rx="10" fill="${last ? C.green : '#fff'}" stroke="${last ? C.green : C.slate}" stroke-width="2.5"/>`
      + `<text x="${r1(cx + wo / 2)}" y="${y + 25}" text-anchor="middle" ${FONT} font-weight="800" font-size="${fs}" fill="${last ? '#fff' : C.ink}">${esc(out)}</text>`;
    if (last) s += sparkle(r1(cx + wo + 18), y + 4, 1.1, C.yellow) + sparkle(r1(cx + wo + 6), y + 34, 0.6, C.pink);
  });
  // a little climber's footsteps up the stairs
  for (let k = 0; k < n; k++) s += `<ellipse cx="${k * 70 + 40}" cy="${H - k * stepH - 8}" rx="6" ry="3.5" fill="#B2BAC6" opacity=".7"/>`;
  return svg(480, H, s, `blending step by step: ${steps.map((st) => `${st[0]} + ${st[1]} = ${st[2]}`).join(', ')}`);
}

// ── PEOPLE ────────────────────────────────────────────────────────────────────────────────
// A person in picture-book style, standing on (x, y). o: {k scale, skin, top, legs, hair:
// 'short'|'long'|'scarf'|'cap'|'grey', scarf, beard, moustache, glasses, look 'up'|'ahead',
// mouth 'smile'|'o'|'sad', tears, arm 'point'|'wave' with angle (degrees from up, + = right), sit}
function person(x, y, o = {}) {
  const k = o.k || 1; const skin = o.skin || SKIN; const top = o.top || C.violet; const legs = o.legs || '#3D4A66';
  const up = o.look === 'up'; const ey = up ? -107 : -104;
  let s = `<g transform="translate(${x} ${y}) scale(${k})">`;
  s += '<ellipse cx="0" cy="1" rx="26" ry="5" fill="#000" opacity=".1"/>';
  if (o.sit) {
    s += `<path d="M-14 -40h28v14c10 0 20 2 24 6l-2 12h-12l-2-6h-36z" fill="${legs}"/><ellipse cx="30" cy="-6" rx="9" ry="5" fill="#3B2F2F"/>`;
  } else {
    s += `<rect x="-13" y="-42" width="10" height="40" rx="5" fill="${legs}"/><rect x="3" y="-42" width="10" height="40" rx="5" fill="${legs}"/>`
      + '<ellipse cx="-9" cy="-3" rx="9" ry="5" fill="#3B2F2F"/><ellipse cx="9" cy="-3" rx="9" ry="5" fill="#3B2F2F"/>';
  }
  // arms: down by default; one may point or wave toward an angle
  const armTo = (side) => {
    if (o.arm && side === (o.armSide || 1)) {
      const a = ((o.armAngle == null ? 30 : o.armAngle) * Math.PI) / 180;
      return [side * 18 + Math.sin(a) * 34, -72 - Math.cos(a) * 34];
    }
    return [side * 25, -44];
  };
  for (const side of [-1, 1]) {
    const [hx, hy] = armTo(side);
    s += `<path d="M${side * 17} -72L${r1(hx)} ${r1(hy)}" stroke="${top}" stroke-width="10" stroke-linecap="round"/><circle cx="${r1(hx)}" cy="${r1(hy)}" r="5.5" fill="${skin}"/>`;
  }
  s += `<path d="M-21 -40c0-26 6-40 21-40s21 14 21 40z" fill="${top}"/>`
    + `<rect x="-6" y="-88" width="12" height="10" rx="4" fill="${skin}"/>`;
  // hair behind the head
  if (o.hair === 'scarf') s += `<path d="M-27 -100c0-22 12-34 27-34s27 12 27 34c0 14-5 24-10 30h-34c-5-6-10-16-10-30z" fill="${o.scarf || C.pink}"/>`;
  if (o.hair === 'long') s += `<path d="M-23 -104c0-18 10-27 23-27s23 9 23 27v22c-6 4-12 4-16 0h-14c-4 4-10 4-16 0z" fill="${o.hairColor || HAIR}"/>`;
  s += `<circle cx="0" cy="-104" r="${o.hair === 'scarf' ? 19 : 22}" fill="${skin}"/>`;
  // hair on top
  if (o.hair === 'scarf') s += `<path d="M-19 -112c3-10 10-15 19-15s16 5 19 15c-5-3-11-5-19-5s-14 2-19 5z" fill="${o.scarf || C.pink}" stroke="#fff" stroke-width="1" opacity=".95"/>`;
  else if (o.hair === 'cap') s += `<path d="M-22 -110c0-14 10-22 22-22s22 8 22 22z" fill="${o.cap || C.skyD}"/><rect x="-24" y="-112" width="48" height="6" rx="3" fill="${o.cap || C.skyD}"/>`;
  else if (o.hair === 'grey') s += `<path d="M-22 -106c-2-14 8-24 22-24s24 10 22 24c-4-8-12-10-22-10s-18 2-22 10z" fill="#D5D9E0"/>`;
  else s += `<path d="M-22 -106c-2-16 8-26 22-26s24 10 22 26c-4-9-11-12-22-12s-18 3-22 12z" fill="${o.hairColor || HAIR}"/>`;
  // face
  s += `<circle cx="-8" cy="${ey}" r="3.2" fill="#2B2521"/><circle cx="8" cy="${ey}" r="3.2" fill="#2B2521"/><circle cx="-7" cy="${ey - 1.2}" r="1.1" fill="#fff"/><circle cx="9" cy="${ey - 1.2}" r="1.1" fill="#fff"/>`
    + `<ellipse cx="-13" cy="${ey + 8}" rx="4.5" ry="2.8" fill="${C.pink}" opacity=".55"/><ellipse cx="13" cy="${ey + 8}" rx="4.5" ry="2.8" fill="${C.pink}" opacity=".55"/>`;
  if (o.glasses) s += `<g fill="none" stroke="#2B2521" stroke-width="1.8"><circle cx="-8" cy="${ey}" r="6"/><circle cx="8" cy="${ey}" r="6"/><path d="M-2 ${ey}h4"/></g>`;
  if (o.beard) s += `<path d="M-17 ${ey + 6}c2 14 9 20 17 20s15-6 17-20c-5 6-10 7-17 7s-12-1-17-7z" fill="${o.beard}"/>`;
  if (o.moustache) s += `<path d="M-9 ${ey + 10}c4-3 7-3 9 0 2-3 5-3 9 0-3 3-6 3-9 1-3 2-6 2-9-1z" fill="${o.moustache}"/>`;
  const my = ey + 13;
  if (o.mouth === 'o') s += `<ellipse cx="0" cy="${my}" rx="3.6" ry="4.6" fill="#8A2E2E"/>`;
  else if (o.mouth === 'sad') s += `<path d="M-6 ${my + 3}c4-5 8-5 12 0" stroke="#8A2E2E" stroke-width="2.4" fill="none" stroke-linecap="round"/>`;
  else if (o.mouth === 'grin') s += `<path d="M-8 ${my - 2}c4 7 12 7 16 0z" fill="#8A2E2E"/><path d="M-6 ${my - 1}h12" stroke="#fff" stroke-width="2"/>`;
  else s += `<path d="M-6 ${my - 1}c4 5 8 5 12 0" stroke="#8A2E2E" stroke-width="2.4" fill="none" stroke-linecap="round"/>`;
  if (o.tears) s += `<path d="M-10 ${ey + 5}c-3 5-3 8 0 9 3-1 3-4 0-9zM10 ${ey + 5}c-3 5-3 8 0 9 3-1 3-4 0-9z" fill="#74B9FF"/>`;
  return `${s}</g>`;
}

// ── SCENERY ───────────────────────────────────────────────────────────────────────────────
const sunFace = (x, y, r) => `<g transform="translate(${x} ${y})">${[0, 45, 90, 135, 180, 225, 270, 315].map((d) => {
  const a = (d * Math.PI) / 180; return `<line x1="${r1(Math.cos(a) * r * 1.3)}" y1="${r1(Math.sin(a) * r * 1.3)}" x2="${r1(Math.cos(a) * r * 1.75)}" y2="${r1(Math.sin(a) * r * 1.75)}" stroke="${C.yellow}" stroke-width="4.5" stroke-linecap="round"/>`;
}).join('')}<circle r="${r}" fill="${C.yellow}"/><circle cx="${r1(-r * 0.32)}" cy="${r1(-r * 0.12)}" r="${r1(r * 0.1)}" fill="#7A4B00"/><circle cx="${r1(r * 0.32)}" cy="${r1(-r * 0.12)}" r="${r1(r * 0.1)}" fill="#7A4B00"/>`
  + `<path d="M${r1(-r * 0.4)} ${r1(r * 0.2)}c${r1(r * 0.25)} ${r1(r * 0.35)} ${r1(r * 0.55)} ${r1(r * 0.35)} ${r1(r * 0.8)} 0" stroke="#7A4B00" stroke-width="2.4" fill="none" stroke-linecap="round"/>`
  + `<circle cx="${r1(-r * 0.6)}" cy="${r1(r * 0.2)}" r="${r1(r * 0.14)}" fill="${C.orange}" opacity=".5"/><circle cx="${r1(r * 0.6)}" cy="${r1(r * 0.2)}" r="${r1(r * 0.14)}" fill="${C.orange}" opacity=".5"/></g>`;
const cloud = (x, y, k = 1) => `<g transform="translate(${x} ${y}) scale(${k})" fill="#fff"><ellipse cx="0" cy="4" rx="28" ry="15"/><ellipse cx="22" cy="-8" rx="22" ry="18"/><ellipse cx="46" cy="4" rx="24" ry="14"/></g>`;
const flower = (x, y, c, k = 1) => `<g transform="translate(${x} ${y}) scale(${k})"><path d="M0 0v14" stroke="#3E9E5A" stroke-width="2.5"/>${[0, 72, 144, 216, 288].map((d) => `<circle cx="${r1(Math.sin((d * Math.PI) / 180) * 5)}" cy="${r1(-Math.cos((d * Math.PI) / 180) * 5)}" r="4" fill="${c}"/>`).join('')}<circle r="3" fill="${C.yellow}"/></g>`;
const butterfly = (x, y, c, k = 1) => `<g transform="translate(${x} ${y}) scale(${k})"><ellipse cx="-6" cy="-3" rx="7" ry="9" fill="${c}" transform="rotate(-25 -6 -3)"/><ellipse cx="6" cy="-3" rx="7" ry="9" fill="${c}" transform="rotate(25 6 -3)"/><ellipse cx="-5" cy="6" rx="4.5" ry="5" fill="${c}" opacity=".8"/><ellipse cx="5" cy="6" rx="4.5" ry="5" fill="${c}" opacity=".8"/><rect x="-1.4" y="-8" width="2.8" height="16" rx="1.4" fill="#2D3436"/></g>`;
const birdsV = (x, y, k = 1) => `<path transform="translate(${x} ${y}) scale(${k})" d="M0 0q6-6 12 0q6-6 12 0M30 -10q5-5 10 0q5-5 10 0" fill="none" stroke="#5B6472" stroke-width="2.4" stroke-linecap="round"/>`;
const meadow = (y, w = 480) => `<path d="M0 ${y}c${w * 0.17}-14 ${w * 0.33}-14 ${w * 0.5}-6s${w * 0.33} 10 ${w * 0.5}-4v${240 - y}H0z" fill="#9BE08A"/><path d="M0 ${y + 16}c${w * 0.19}-8 ${w * 0.42}-6 ${w * 0.62} 0s${w * 0.27} 2 ${w * 0.38}-4v${224 - y}H0z" fill="#7CCB6E"/>`;
function bird(x, y, k = 1) {
  return `<g transform="translate(${x} ${y}) scale(${k})">`
    + '<ellipse cx="0" cy="0" rx="20" ry="14" fill="#FFD43B"/><ellipse cx="2" cy="4" rx="11" ry="7" fill="#FFF3B0"/><circle cx="16" cy="-10" r="10" fill="#FFD43B"/>'
    + '<path d="M-8 -2c-6 8-16 8-22 4 8-2 14-6 18-12z" fill="#F2A20C"/>'
    + '<path d="M25 -12l10-2-10 6z" fill="#F08C00"/><path d="M25 -9l9 3-9 0z" fill="#E8590C"/>'
    + '<circle cx="18" cy="-12" r="2.4" fill="#2B2521"/><circle cx="18.8" cy="-12.8" r=".8" fill="#fff"/><ellipse cx="13" cy="-6" rx="3" ry="2" fill="#FF8FB1" opacity=".7"/>'
    + '<path d="M-2 13v6M6 13v6" stroke="#8A5A3B" stroke-width="2.5" stroke-linecap="round"/></g>';
}
const note = (x, y, c = C.violet) => `<g transform="translate(${x} ${y})" fill="${c}"><ellipse cx="0" cy="12" rx="6.5" ry="5" transform="rotate(-20 0 12)"/><rect x="5" y="-10" width="2.8" height="22"/><path d="M7.5 -10c6 2 9 6 8 12-2-4-5-6-8-6z"/></g>`;
function tree(x, y, k = 1) {
  return `<g transform="translate(${x} ${y}) scale(${k})"><path d="M-11 0h22l-5 -82h-12z" fill="${C.brown}"/>`
    + '<circle cx="0" cy="-104" r="46" fill="#4FB45E"/><circle cx="-34" cy="-80" r="30" fill="#62C46F"/><circle cx="34" cy="-82" r="32" fill="#45A653"/>'
    + '<circle cx="-14" cy="-120" r="5" fill="#FF6B6B"/><circle cx="20" cy="-100" r="5" fill="#FF6B6B"/><circle cx="-30" cy="-86" r="5" fill="#FF6B6B"/></g>';
}
function pine(x, y, k = 1, c = '#2F8F57') {
  return `<g transform="translate(${x} ${y}) scale(${k})"><rect x="-4" y="-12" width="8" height="14" fill="${C.brown}"/>`
    + `<path d="M0 -74l22 32h-10l17 26h-58l17-26h-10z" fill="${c}"/><path d="M0 -74l8 12" stroke="#fff" stroke-width="2" opacity=".35"/></g>`;
}
const skyDefs = (id, a, b) => `<defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs>`;
function lakeBack() {
  return skyDefs('qsky2', '#9ED8FF', '#E8F6FF')
    + '<defs><linearGradient id="qlake" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#48C1E8"/><stop offset="1" stop-color="#1F8FBF"/></linearGradient></defs>'
    + '<rect width="480" height="240" rx="16" fill="url(#qsky2)"/>' + sunFace(420, 46, 20) + cloud(60, 40, 0.8) + cloud(250, 30, 0.6) + birdsV(150, 36, 0.9)
    + '<path d="M-10 156l90-96 60 54 70-82 92 104 50-44 88 66v20H-10z" fill="#8FA4BF"/>'
    + '<path d="M80 60l-24 26 14-4 10 10 12-14 10 6z" fill="#fff"/><path d="M210 32l-26 30 14-4 12 12 12-12 14 8z" fill="#fff"/><path d="M352 92l-18 18 10-2 8 8 8-8 10 4z" fill="#fff"/>'
    + '<path d="M-10 166l120-50 80 40 90-46 110 56 100-30v40H-10z" fill="#6F8BA8"/>'
    + '<ellipse cx="240" cy="190" rx="236" ry="36" fill="url(#qlake)"/>'
    + '<path d="M130 186h60M260 194h80M200 204h50M330 180h40" stroke="#fff" stroke-width="3" stroke-linecap="round" opacity=".6"/>'
    + '<path d="M0 206c40-10 70-8 100 4s-60 30-100 30z" fill="#7CCB6E"/><path d="M480 202c-50-10-90-6-120 6s70 32 120 32z" fill="#7CCB6E"/>'
    + pine(28, 214, 1) + pine(60, 222, 0.8, '#3BA265') + pine(424, 216, 1) + pine(456, 222, 0.85, '#3BA265')
    + flower(96, 222, C.pink, 0.9) + flower(380, 226, C.yellow, 0.9);
}
const SCENES = {
  songbird: () => {
    let s = skyDefs('qsky1', '#B8E2FF', '#EEF8FF') + '<rect width="480" height="240" rx="16" fill="url(#qsky1)"/>' + sunFace(430, 42, 19) + cloud(250, 36, 0.8) + meadow(196);
    // the tree with a long branch reaching right; the songbird on the branch, singing
    s += '<path d="M60 214h26l-4-128h-18z" fill="#A0673E"/><path d="M76 118c40-6 90-6 140 6" stroke="#A0673E" stroke-width="9" stroke-linecap="round" fill="none"/>'
      + '<circle cx="70" cy="74" r="52" fill="#4FB45E"/><circle cx="34" cy="96" r="30" fill="#62C46F"/><circle cx="110" cy="88" r="32" fill="#45A653"/>'
      + '<circle cx="54" cy="58" r="5" fill="#FF6B6B"/><circle cx="92" cy="72" r="5" fill="#FF6B6B"/><ellipse cx="204" cy="118" rx="14" ry="6" fill="#62C46F"/>'
      + bird(182, 98, 1.05) + note(222, 56) + note(248, 34, C.skyD) + note(266, 70, C.coral);
    // the storyteller points to the bird; Pinky (pink headscarf, purple top) looks up in surprise; a child in orange with glasses
    s += person(300, 224, { k: 0.86, hair: 'grey', beard: '#E3E6EC', top: '#6C7A89', look: 'up', arm: 'point', armSide: -1, armAngle: -40 })
      + person(368, 224, { k: 0.74, hair: 'scarf', scarf: C.pink, top: '#8E5BC6', look: 'up', mouth: 'o' })
      + person(430, 224, { k: 0.66, top: C.orange, look: 'up', glasses: true })
      + flower(20, 226, C.coral) + flower(240, 230, C.yellow) + butterfly(150, 168, C.pink, 0.9) + butterfly(470, 150, C.sky, 0.7);
    return svg(480, 240, s, 'Pinky looks up at a yellow songbird singing on a tree branch');
  },
  kite_tree: () => {
    let s = skyDefs('qsky3', '#B8E2FF', '#EEF8FF') + '<rect width="480" height="240" rx="16" fill="url(#qsky3)"/>' + sunFace(56, 46, 18) + cloud(300, 34, 0.7) + meadow(200);
    s += tree(190, 210, 1.25);
    // the kite stuck high in the tree, its tail of bows hanging down
    s += '<g transform="translate(214 62) rotate(18)"><path d="M0 -32l24 32-24 36-24-36z" fill="#FF6B6B"/><path d="M0 -32l24 32H0z" fill="#FECA57"/><path d="M0 4l-24-4 24 36z" fill="#54A0FF"/><path d="M0 -32v68M-24 0h48" stroke="#fff" stroke-width="2.5"/></g>'
      + '<path d="M222 100c12 26-6 46 6 72" stroke="#3D4A66" stroke-width="2" fill="none"/>'
      + '<path d="M218 120l-6-5v10zM218 120l6-5v10zM222 146l-6-5v10zM222 146l6-5v10zM226 168l-6-5v10zM226 168l6-5v10z" fill="#A55EEA"/>';
    // a boy looking up at it, pointing
    s += person(340, 226, { k: 0.86, top: C.skyD, look: 'up', mouth: 'o', arm: 'point', armSide: -1, armAngle: -35 })
      + flower(410, 228, C.pink) + flower(440, 232, C.yellow) + flower(60, 230, C.violet) + butterfly(420, 120, C.orange, 0.9);
    return svg(480, 240, s, 'a boy looks up at a kite stuck high in a tree');
  },
  lake: () => {
    const s = lakeBack() + '<path d="M300 184l34 0-7 8h-20z" fill="#C0793F"/><path d="M316 184v-20l14 16z" fill="#fff"/><path d="M316 184v-16l-10 14z" fill="#FF6B6B"/>';
    return svg(480, 240, s, 'a lake with snowy mountains and pine trees');
  },
  // the story: a boy crying by the lake, and a man bending to help him
  crying_boy: () => {
    let s = lakeBack();
    s += '<ellipse cx="212" cy="226" rx="40" ry="12" fill="#9AA4B1"/><ellipse cx="206" cy="220" rx="34" ry="12" fill="#B4BCC7"/>';
    s += person(214, 222, { k: 0.72, sit: true, top: C.orange, mouth: 'sad', tears: true })
      + person(290, 230, { k: 0.95, top: '#4A69BD', hair: 'short', moustache: HAIR, look: 'ahead', arm: 'point', armSide: -1, armAngle: -120 });
    return svg(480, 240, s, 'a small boy crying by the lake and a man bending to help him');
  },
  // partner reading: two children share one book; a stopwatch shows the minute
  pair_reading: () => {
    let s = '<rect width="480" height="230" rx="16" fill="#FFF6E5"/><rect x="0" y="170" width="480" height="60" rx="0" fill="#F4E1C1"/>'
      + '<rect x="30" y="30" width="120" height="80" rx="8" fill="#2F4F4F"/><path d="M48 60h40M48 76h60M48 92h30" stroke="#fff" stroke-width="3" stroke-linecap="round" opacity=".8"/>';
    s += person(200, 214, { k: 0.86, top: C.coral, hair: 'short', mouth: 'smile', arm: 'point', armSide: 1, armAngle: 120 })
      + person(290, 214, { k: 0.86, top: C.aqua, hair: 'long', mouth: 'o', arm: 'point', armSide: -1, armAngle: -120 });
    // the book between them
    s += '<path d="M245 150c-14-6-30-6-42-2v34c12-4 28-4 42 2z" fill="#fff" stroke="#54A0FF" stroke-width="3"/><path d="M245 150c14-6 30-6 42-2v34c-12-4-28-4-42 2z" fill="#fff" stroke="#54A0FF" stroke-width="3"/>'
      + '<path d="M212 160h24M212 168h22M254 160h24M254 168h22" stroke="#B2BAC6" stroke-width="2"/>';
    // a stopwatch
    s += '<g transform="translate(404 92)"><rect x="-6" y="-52" width="12" height="10" rx="3" fill="#FF6B6B"/><circle r="40" fill="#FF6B6B"/><circle r="32" fill="#fff"/>'
      + '<path d="M0 0V-24" stroke="#303749" stroke-width="5" stroke-linecap="round"/><path d="M0 -32A32 32 0 0 1 32 0H0z" fill="#FECA57" opacity=".6"/><circle r="5" fill="#303749"/></g>'
      + sparkle(350, 40, 0.8) + sparkle(460, 150, 0.6, C.pink);
    return svg(480, 230, s, 'two children reading one book together, with a stopwatch');
  },
  // Bunty's home: the wall clock and the digital clock on the table, both at the lesson's time
  bunty_home: (spec) => {
    const t = spec.time || '9:00';
    let s = '<rect width="480" height="250" rx="16" fill="#FFF3DC"/><rect x="0" y="196" width="480" height="54" fill="#E8C9A0"/><path d="M0 196h480" stroke="#D2AE80" stroke-width="3"/>'
      + '<rect x="300" y="26" width="150" height="104" rx="8" fill="#BDE6FF" stroke="#fff" stroke-width="6"/><path d="M375 26v104M300 78h150" stroke="#fff" stroke-width="5"/>' + sunFace(420, 52, 13)
      + '<path d="M296 22h158" stroke="#FF8FB1" stroke-width="8" stroke-linecap="round"/><path d="M300 26c10 40 4 70-8 104M450 26c-10 40-4 70 8 104" stroke="#FF8FB1" stroke-width="10" fill="none" opacity=".75"/>';
    // the wall clock
    s += clockFace(140, 78, 54, t, { style: 'wall' });
    // the table and its digital clock
    s += '<rect x="196" y="150" width="190" height="14" rx="6" fill="#B87A48"/><rect x="210" y="164" width="12" height="40" fill="#A0673E"/><rect x="360" y="164" width="12" height="40" fill="#A0673E"/>'
      + digitalClock(236, 108, 110, 42, spec.digital || t)
      + '<rect x="350" y="122" width="22" height="28" rx="5" fill="#FF9F43"/><circle cx="361" cy="112" r="14" fill="#4FB45E"/><circle cx="352" cy="118" r="9" fill="#62C46F"/>';
    s += person(60, 232, { k: 0.78, top: C.coral, look: 'up', arm: 'point', armSide: 1, armAngle: 40 })
      + person(440, 236, { k: 0.72, top: C.skyD, look: 'ahead', mouth: 'o' });
    return svg(480, 250, s, `a room with a wall clock and a digital clock on the table, both showing ${spec.digital || t}`);
  },
};
function scene(spec) {
  const f = SCENES[spec.scene];
  if (!f) throw new Error(`scene: no drawing for "${spec.scene}"`);
  return f(spec);
}

// ── POSTERS AND BOOKS ─────────────────────────────────────────────────────────────────────
// wrap text for SVG at about n characters a line
function wrap(text, n) {
  const out = []; let line = '';
  for (const w of String(text).split(/\s+/)) {
    if ((line + ' ' + w).trim().length > n && line) { out.push(line); line = w; } else line = (line + ' ' + w).trim();
  }
  if (line) out.push(line);
  return out;
}
const POSTER_ICON = {
  puppet: (x, y) => `<g transform="translate(${x} ${y})"><path d="M-14 -16h28" stroke="#A0673E" stroke-width="3"/><path d="M-10 -16l6 10M10 -16l-6 10M0 -16v6" stroke="#B2BAC6" stroke-width="1.4"/><circle cx="0" cy="-2" r="8" fill="${SKIN}"/><path d="M-8 -6c2-6 14-6 16 0z" fill="${C.coral}"/><path d="M-9 6h18l3 12h-24z" fill="${C.violet}"/><circle cx="-3" cy="-2" r="1.3" fill="#2B2521"/><circle cx="3" cy="-2" r="1.3" fill="#2B2521"/></g>`,
  fireworks: (x, y) => `<g transform="translate(${x} ${y})">${[0, 45, 90, 135, 180, 225, 270, 315].map((d, i) => { const a = (d * Math.PI) / 180; return `<line x1="${r1(Math.cos(a) * 5)}" y1="${r1(Math.sin(a) * 5)}" x2="${r1(Math.cos(a) * 16)}" y2="${r1(Math.sin(a) * 16)}" stroke="${TILE[i % TILE.length]}" stroke-width="3" stroke-linecap="round"/>`; }).join('')}<circle r="3.5" fill="${C.yellow}"/></g>`,
  magic: (x, y) => `<g transform="translate(${x} ${y})"><ellipse cx="0" cy="12" rx="17" ry="4" fill="#2D3436"/><path d="M-11 12V-8h22v20z" fill="#2D3436"/><rect x="-11" y="2" width="22" height="5" fill="${C.coral}"/><path d="M8 -10l12-10" stroke="#2D3436" stroke-width="3" stroke-linecap="round"/>${sparkle(20, -20, 0.6, C.yellow)}${sparkle(-16, -14, 0.45, C.pink)}</g>`,
};
// the textbook's Fun Fair poster: bunting on top, one row per show with its own small clock
function poster(spec) {
  const items = spec.items; const rowH = 66; const H = 92 + items.length * rowH + 14;
  let s = `<rect x="4" y="4" width="472" height="${H - 8}" rx="18" fill="#FFF8EC" stroke="${C.orange}" stroke-width="4"/>`;
  // bunting
  s += '<path d="M14 20q226 30 452 0" stroke="#A0673E" stroke-width="2" fill="none"/>';
  for (let i = 0; i < 12; i++) {
    const x = 26 + i * 38; const y = 20 + Math.sin((i / 11) * Math.PI) * 13;
    s += `<path d="M${x - 11} ${r1(y)}h22l-11 20z" fill="${TILE[i % TILE.length]}"/>`;
  }
  s += `<text x="240" y="76" text-anchor="middle" ${FONT} font-weight="800" font-size="30" fill="${C.coralD}" letter-spacing="3">${esc(spec.title || '')}</text>`;
  items.forEach((it, k) => {
    const y = 92 + k * rowH;
    s += `<rect x="20" y="${y}" width="440" height="${rowH - 10}" rx="14" fill="${['#E3F0FF', '#FFE3E3', '#EFE3FF', '#DDF7EC'][k % 4]}"/>`;
    if (POSTER_ICON[it.icon]) s += POSTER_ICON[it.icon](52, y + rowH / 2 - 5);
    s += `<text x="84" y="${y + rowH / 2 + 3}" ${FONT} font-weight="800" font-size="21" fill="${C.ink}">${esc(it.text)}</text>`
      + `<text x="352" y="${y + rowH / 2 + 3}" text-anchor="end" ${FONT} font-weight="800" font-size="21" fill="${C.blue}">${esc(it.time)}</text>`
      + clockFace(410, y + rowH / 2 - 5, 24, it.time, { style: 'mini', rim: C.sky });
  });
  return svg(480, H, s, `${spec.title} poster: ${items.map((i) => `${i.text} ${i.time}`).join(', ')}`);
}
// the board's prediction: the book's title and picture, and a thought bubble for the guess
function predict(spec) {
  let s = '<rect x="14" y="18" width="190" height="210" rx="12" fill="#000" opacity=".12"/>'
    + '<rect x="10" y="12" width="190" height="210" rx="12" fill="#54A0FF"/><rect x="10" y="12" width="20" height="210" rx="6" fill="#2E86DE"/>'
    + '<rect x="40" y="72" width="146" height="112" rx="10" fill="#D9F2FF"/>' + sunFace(160, 92, 9)
    + '<path d="M40 162c40-8 100-8 146 0v22H40z" fill="#9BE08A"/><path d="M70 176h10l-2-52h-6z" fill="#A0673E"/><circle cx="75" cy="114" r="24" fill="#4FB45E"/>'
    + '<path d="M78 130c26-2 50 0 70 4" stroke="#A0673E" stroke-width="5" stroke-linecap="round"/>' + bird(138, 118, 0.6) + note(156, 98, '#fff');
  wrap(spec.title, 16).slice(0, 2).forEach((l, i) => { s += `<text x="115" y="${42 + i * 22}" text-anchor="middle" ${FONT} font-weight="800" font-size="18" fill="#fff">${esc(l)}</text>`; });
  // thought bubble with a question mark and sparkles
  s += '<circle cx="218" cy="196" r="7" fill="#fff" stroke="#A55EEA" stroke-width="3"/><circle cx="238" cy="174" r="11" fill="#fff" stroke="#A55EEA" stroke-width="3"/>'
    + '<path d="M266 150c-30 0-36-40-10-48 0-30 40-40 60-20 16-24 64-20 72 6 30-2 44 34 22 50 14 26-14 50-40 40-14 22-60 22-72 0-20 8-36-6-32-28z" fill="#fff" stroke="#A55EEA" stroke-width="3.5"/>'
    + `<circle cx="438" cy="70" r="13" fill="${C.yellow}"/><text x="438" y="77" text-anchor="middle" ${FONT} font-weight="800" font-size="18" fill="#7A4B00">?</text>`
    + sparkle(300, 70, 0.7, C.pink) + sparkle(420, 196, 0.6, C.sky);
  // the prompt, each word on its own line where it is long, inside the bubble
  const pr = wrap(String(spec.prompt).replace(/_{3,}/g, '______'), 11);
  pr.forEach((l, i) => { s += `<text x="356" y="${132 + i * 24 - (pr.length - 1) * 12}" text-anchor="middle" ${FONT} font-weight="800" font-size="17" fill="#7B3FC4">${esc(l)}</text>`; });
  return svg(480, 236, s, `book cover "${spec.title}" and a thought bubble: ${spec.prompt}`);
}
const PICTURE = { sun: (x, y) => sunFace(x, y, 14) };
// a picture dictionary open at the word's letter: alphabet tabs, a magnifying glass on the word
function dictionary(spec) {
  const letter = String(spec.word || '?').charAt(0).toUpperCase();
  let s = '<path d="M240 34c-50-18-130-18-222 0v178c92-18 172-18 222 0z" fill="#FFF8E8" stroke="#E0A84B" stroke-width="3"/>'
    + '<path d="M240 34c50-18 130-18 222 0v178c-92-18-172-18-222 0z" fill="#FFFDF6" stroke="#E0A84B" stroke-width="3"/>'
    + '<path d="M240 34v178" stroke="#E0A84B" stroke-width="3"/>';
  // alphabet tabs down the right edge, the word's letter pulled out
  ['P', 'Q', 'R', 'S', 'T', 'U'].forEach((L, i) => {
    const on = L === letter; const y = 44 + i * 26;
    s += `<rect x="${on ? 452 : 458}" y="${y}" width="${on ? 26 : 18}" height="22" rx="5" fill="${on ? C.orange : TILE[i % TILE.length]}" opacity="${on ? 1 : 0.55}"/>`
      + (on ? `<text x="465" y="${y + 16}" text-anchor="middle" ${FONT} font-weight="800" font-size="14" fill="#fff">${esc(L)}</text>` : '');
  });
  s += `<text x="128" y="104" text-anchor="middle" ${FONT} font-weight="800" font-size="80" fill="${C.orange}">${esc(letter)}</text>`
    + `<text x="128" y="140" text-anchor="middle" ${FONT} font-weight="700" font-size="20" fill="${C.slate}">${esc(letter.toLowerCase())}a  ${esc(letter.toLowerCase())}e  ${esc(letter.toLowerCase())}u …</text>`
    + `<rect x="262" y="58" width="150" height="34" rx="9" fill="${C.mint}"/><text x="274" y="82" ${FONT} font-weight="800" font-size="21" fill="${C.green}">${esc(spec.word)}</text>`;
  if (PICTURE[spec.picture]) s += PICTURE[spec.picture](128, 180);   // the word's picture, on the letter's page
  const rest = String(spec.entry || '').replace(new RegExp(`^${String(spec.word).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*,?\\s*`), '');
  wrap(rest, 18).slice(0, 4).forEach((l, i) => { s += `<text x="266" y="${122 + i * 23}" ${FONT} font-weight="500" font-size="17" fill="${C.ink}">${esc(l)}</text>`; });
  // the magnifying glass over the word
  s += '<circle cx="388" cy="70" r="24" fill="#fff" fill-opacity=".25" stroke="#303749" stroke-width="5"/><path d="M405 88l20 20" stroke="#303749" stroke-width="8" stroke-linecap="round"/>';
  return svg(480, 228, s, `dictionary entry: ${spec.entry}`);
}

// ── ROADS, BEES, PARKS ────────────────────────────────────────────────────────────────────
// Pictures for more lessons in the same style: a road with a zebra crossing, traffic lights and
// road signs; bees in a line and cars on a road for positions; a park with its signboard.
const URDU = "font-family=\"'Noto Nastaliq Urdu',Inter,sans-serif\"";
const isUr = (t) => /[؀-ۿ]/.test(String(t));
const tfont = (t) => (isUr(t) ? URDU : FONT);
// a traffic light: red on top, yellow, green; each light may carry a word beside it
function trafficLight(x, y, k = 1, { faces = true } = {}) {
  let s = `<g transform="translate(${x} ${y}) scale(${k})"><rect x="-7" y="96" width="14" height="96" rx="4" fill="#5B6472"/><rect x="-22" y="186" width="44" height="10" rx="5" fill="#5B6472"/>`
    + '<rect x="-30" y="0" width="60" height="104" rx="16" fill="#2D3436"/><rect x="-26" y="4" width="52" height="96" rx="13" fill="#3B4450"/>';
  [['#FF4D4D', 20], ['#FECA57', 52], ['#2ECC71', 84]].forEach(([col, cy]) => {
    s += `<circle cx="0" cy="${cy}" r="13" fill="${col}"/><circle cx="-4" cy="${cy - 4}" r="4" fill="#fff" opacity=".45"/>`;
    if (faces) s += `<circle cx="-4" cy="${cy - 1}" r="1.6" fill="#2D3436"/><circle cx="4" cy="${cy - 1}" r="1.6" fill="#2D3436"/><path d="M-4 ${cy + 4}c2.5 2.5 5.5 2.5 8 0" stroke="#2D3436" stroke-width="1.6" fill="none" stroke-linecap="round"/>`;
  });
  return `${s}</g>`;
}
function trafficLightVisual(spec) {
  const L = spec.labels || {};
  let s = trafficLight(70, 8, 1.1);
  const tag = (y, col, word) => (word ? `<path d="M108 ${y}h14" stroke="${col}" stroke-width="3" stroke-linecap="round"/><rect x="124" y="${y - 19}" width="${Math.max(84, String(word).length * 14 + 28)}" height="38" rx="19" fill="${col}"/>`
    + `<text x="${124 + Math.max(84, String(word).length * 14 + 28) / 2}" y="${y + 7}" text-anchor="middle" ${tfont(word)} font-weight="800" font-size="20" fill="#fff">${esc(word)}</text>` : '');
  s += tag(30, '#E04F4F', L.red) + tag(65, '#E0A100', L.yellow) + tag(100, '#1E9E57', L.green);
  return svg(300, 222, s, `traffic light${L.red ? `: red ${L.red}` : ''}${L.green ? `, green ${L.green}` : ''}`);
}
// road signs, drawn as their shapes: r is the sign's size
const SIGN = {
  stop: (r) => `<path d="${[...Array(8)].map((_, i) => { const a = Math.PI / 8 + (i * Math.PI) / 4; return `${i ? 'L' : 'M'}${r1(Math.cos(a) * r)} ${r1(Math.sin(a) * r)}`; }).join('')}z" fill="#E53935" stroke="#fff" stroke-width="${r1(r * 0.08)}"/><text x="0" y="${r1(r * 0.24)}" text-anchor="middle" ${FONT} font-weight="800" font-size="${r1(r * 0.6)}" fill="#fff">STOP</text>`,
  parking: (r) => `<rect x="${-r}" y="${-r}" width="${2 * r}" height="${2 * r}" rx="${r1(r * 0.22)}" fill="#1E64C8" stroke="#fff" stroke-width="${r1(r * 0.08)}"/><text x="0" y="${r1(r * 0.42)}" text-anchor="middle" ${FONT} font-weight="800" font-size="${r1(r * 1.25)}" fill="#fff">P</text>`,
  turn_left: (r) => `<circle r="${r}" fill="#1E64C8" stroke="#fff" stroke-width="${r1(r * 0.08)}"/><path d="M${r1(r * 0.3)} ${r1(r * 0.55)}V${r1(-r * 0.05)}H${r1(-r * 0.25)}" stroke="#fff" stroke-width="${r1(r * 0.2)}" fill="none" stroke-linejoin="round"/><path d="M${r1(-r * 0.55)} ${r1(-r * 0.05)}l${r1(r * 0.36)} ${r1(-r * 0.3)}v${r1(r * 0.6)}z" fill="#fff"/>`,
  no_cycling: (r) => `<circle r="${r}" fill="#fff" stroke="#E53935" stroke-width="${r1(r * 0.18)}"/><g stroke="#2D3436" stroke-width="${r1(r * 0.08)}" fill="none"><circle cx="${r1(-r * 0.36)}" cy="${r1(r * 0.2)}" r="${r1(r * 0.24)}"/><circle cx="${r1(r * 0.36)}" cy="${r1(r * 0.2)}" r="${r1(r * 0.24)}"/><path d="M${r1(-r * 0.36)} ${r1(r * 0.2)}L${r1(-r * 0.08)} ${r1(-r * 0.2)}H${r1(r * 0.22)}L${r1(r * 0.36)} ${r1(r * 0.2)}M${r1(-r * 0.08)} ${r1(-r * 0.2)}L${r1(r * 0.02)} ${r1(r * 0.2)}"/></g>`,
  hump: (r) => `<path d="M0 ${r1(-r)}L${r1(r * 1.05)} ${r1(r * 0.8)}H${r1(-r * 1.05)}z" fill="#fff" stroke="#E53935" stroke-width="${r1(r * 0.16)}" stroke-linejoin="round"/><path d="M${r1(-r * 0.5)} ${r1(r * 0.45)}q${r1(r * 0.5)} ${r1(-r * 0.6)} ${r1(r)} 0z" fill="#2D3436"/>`,
  crossroads: (r) => `<path d="M0 ${r1(-r)}L${r1(r * 1.05)} ${r1(r * 0.8)}H${r1(-r * 1.05)}z" fill="#fff" stroke="#E53935" stroke-width="${r1(r * 0.16)}" stroke-linejoin="round"/><path d="M0 ${r1(-r * 0.35)}v${r1(r * 0.9)}M${r1(-r * 0.36)} ${r1(r * 0.12)}h${r1(r * 0.72)}" stroke="#2D3436" stroke-width="${r1(r * 0.16)}"/>`,
  children: (r) => `<path d="M0 ${r1(-r)}L${r1(r * 1.05)} ${r1(r * 0.8)}H${r1(-r * 1.05)}z" fill="#fff" stroke="#E53935" stroke-width="${r1(r * 0.16)}" stroke-linejoin="round"/>`
    + `<g fill="#2D3436"><circle cx="${r1(-r * 0.2)}" cy="${r1(-r * 0.25)}" r="${r1(r * 0.11)}"/><circle cx="${r1(r * 0.22)}" cy="${r1(-r * 0.15)}" r="${r1(r * 0.1)}"/><path d="M${r1(-r * 0.32)} ${r1(-r * 0.1)}h${r1(r * 0.24)}l${r1(r * 0.08)} ${r1(r * 0.5)}h${r1(-r * 0.4)}z"/><path d="M${r1(r * 0.1)} ${r1(-r * 0.02)}h${r1(r * 0.24)}l${r1(r * 0.06)} ${r1(r * 0.48)}h${r1(-r * 0.36)}z"/></g>`,
};
const roadSign = (kind, x, y, r) => (SIGN[kind] ? `<g transform="translate(${x} ${y})">${SIGN[kind](r)}</g>` : '');
function roadSigns(spec) {
  const signs = spec.signs; const cols = Math.min(3, signs.length); const rows = Math.ceil(signs.length / cols);
  const cw = 480 / cols; const rh = 118; let s = '';
  signs.forEach((g, i) => {
    const cx = (i % cols) * cw + cw / 2; const top = Math.floor(i / cols) * rh;
    s += `<rect x="${r1((i % cols) * cw + 6)}" y="${top + 4}" width="${r1(cw - 12)}" height="${rh - 10}" rx="14" fill="${['#FFF1F0', '#EEF4FF', '#FFF8E8'][i % 3]}"/>`
      + `<rect x="${r1(cx - 3)}" y="${top + 50}" width="6" height="30" fill="#9AA4B1"/>` + roadSign(g.sign, r1(cx), top + 40, 28)
      + `<text x="${r1(cx)}" y="${top + 100}" text-anchor="middle" ${tfont(g.label)} font-weight="700" font-size="15" fill="${C.ink}">${esc(g.label)}</text>`;
  });
  return svg(480, rows * rh, s, `road signs: ${signs.map((g) => g.label).join(', ')}`);
}
function roadSignOne(spec) { return svg(100, 100, roadSign(spec.sign, 50, 50, 40), `road sign ${spec.sign}`); }
// the three steps for crossing: a child seen from behind, looking right, left, right again
function lookSteps(spec) {
  const steps = spec.steps; const w = 480 / steps.length; let s = '';
  steps.forEach((st, i) => {
    const cx = i * w + w / 2; const right = st.dir === 'right';
    s += `<rect x="${r1(i * w + 6)}" y="4" width="${r1(w - 12)}" height="186" rx="16" fill="${['#E3F0FF', '#FFF1D6', '#DDF7EC'][i % 3]}"/>`
      + `<circle cx="${r1(i * w + 30)}" cy="30" r="15" fill="${TILE[i % TILE.length]}"/><text x="${r1(i * w + 30)}" y="36" text-anchor="middle" ${FONT} font-weight="800" font-size="17" fill="#fff">${i + 1}</text>`
      // the child from behind: shoulders, the back of the head, hair, ears; the head turned toward the arrow
      + `<path d="M${r1(cx - 38)} 150c4-24 18-34 38-34s34 10 38 34z" fill="${C.skyD}"/><rect x="${r1(cx - 12)}" y="140" width="24" height="10" fill="${C.skyD}"/>`
      + `<g transform="rotate(${right ? 14 : -14} ${r1(cx)} 112)"><circle cx="${r1(cx)}" cy="88" r="27" fill="${HAIR}"/><ellipse cx="${r1(cx - 27)}" cy="92" rx="6" ry="9" fill="${SKIN}"/><ellipse cx="${r1(cx + 27)}" cy="92" rx="6" ry="9" fill="${SKIN}"/><rect x="${r1(cx - 9)}" y="110" width="18" height="10" fill="${SKIN}"/></g>`
      + `<path d="M${r1(right ? cx + 30 : cx - 30)} 66h${right ? 22 : -22}" stroke="${C.coral}" stroke-width="7" stroke-linecap="round"/><path d="M${r1(right ? cx + 50 : cx - 50)} 55l${right ? 15 : -15} 11l${right ? -15 : 15} 11z" fill="${C.coral}"/>`
      + `<text x="${r1(cx)}" y="178" text-anchor="middle" ${tfont(st.label)} font-weight="800" font-size="17" fill="${C.ink}">${esc(st.label)}</text>`;
  });
  return svg(480, 194, s, `steps: ${steps.map((st) => st.label).join(', ')}`);
}
// a bee, round and friendly
function bee(x, y, k = 1) {
  return `<g transform="translate(${x} ${y}) scale(${k})">`
    + '<ellipse cx="-4" cy="-16" rx="9" ry="13" fill="#D6EEFF" stroke="#9CC9EE" stroke-width="1.5" transform="rotate(-20 -4 -16)"/><ellipse cx="6" cy="-16" rx="9" ry="13" fill="#D6EEFF" stroke="#9CC9EE" stroke-width="1.5" transform="rotate(20 6 -16)"/>'
    + '<ellipse cx="0" cy="0" rx="19" ry="13" fill="#FECA57"/><rect x="-7" y="-12.5" width="5" height="25" rx="2" fill="#2D3436"/><rect x="3" y="-12" width="5" height="24" rx="2" fill="#2D3436"/>'
    + '<path d="M-19 0l-7 -3v6z" fill="#2D3436"/><circle cx="20" cy="-3" r="9" fill="#FECA57"/><circle cx="22" cy="-5" r="1.8" fill="#2D3436"/><path d="M19 1c2 2 4 2 6 0" stroke="#2D3436" stroke-width="1.4" fill="none" stroke-linecap="round"/>'
    + '<ellipse cx="17" cy="0" rx="2.5" ry="1.6" fill="#FF8FB1" opacity=".8"/><path d="M19 -11l-2 -7M24 -11l2 -7" stroke="#2D3436" stroke-width="1.4"/><circle cx="17" cy="-18" r="1.6" fill="#2D3436"/><circle cx="26" cy="-18" r="1.6" fill="#2D3436"/></g>';
}
// an ordinal number drawn as 1st, 2nd, 3rd: the ending small and raised
const ordinalText = (x, y, n, end, fs, col) => `<text x="${r1(x)}" y="${r1(y)}" text-anchor="middle" ${FONT} font-weight="800" font-size="${fs}" fill="${col}">${esc(n)}<tspan font-size="${r1(fs * 0.55)}" dy="${r1(-fs * 0.38)}">${esc(end)}</tspan></text>`;
const splitOrdinal = (o) => { const m = /^(\d+)(st|nd|rd|th)$/.exec(String(o)); return m ? [m[1], m[2]] : [String(o), '']; };
// a row of bees or children, each with its position above and its word below
function ordinalRow(spec) {
  const items = spec.items; const w = 480 / items.length; let s = '';
  items.forEach((it, i) => {
    const cx = i * w + w / 2; const [n, end] = splitOrdinal(it.ord);
    s += `<rect x="${r1(cx - 24)}" y="4" width="48" height="34" rx="10" fill="${TILE[i % TILE.length]}"/>` + ordinalText(cx, 30, n, end, 20, '#fff');
    s += spec.object === 'child'
      ? person(r1(cx), 162, { k: 0.62, top: TILE[(i + 2) % TILE.length], hair: i % 2 ? 'long' : 'short', look: 'ahead' })
      : bee(r1(cx - 2), 92, Math.min(1.3, w / 52));
    if (it.word) s += `<text x="${r1(cx)}" y="186" text-anchor="middle" ${FONT} font-weight="700" font-size="${w < 70 ? 14 : 16}" fill="${C.ink}">${esc(it.word)}</text>`;
  });
  if (spec.object === 'child') s += '<path d="M0 166h480" stroke="#B2BAC6" stroke-width="3" stroke-dasharray="6 6"/>';
  return svg(480, 196, s, `positions: ${items.map((it) => `${it.ord} ${it.word || ''}`).join(', ')}`);
}
// bees flying in a line to their hive
SCENES.bee_line = () => {
  let s = skyDefs('qsky4', '#C9EBFF', '#F1FAFF') + '<rect width="480" height="240" rx="16" fill="url(#qsky4)"/>' + sunFace(46, 42, 16) + cloud(160, 30, 0.6) + meadow(204);
  s += '<path d="M480 40c-60 6-100 10-150 26" stroke="#A0673E" stroke-width="10" fill="none" stroke-linecap="round"/><circle cx="440" cy="30" r="26" fill="#4FB45E"/><circle cx="470" cy="56" r="22" fill="#45A653"/>';
  s += '<g transform="translate(372 92)"><path d="M-30 -24q30-30 60 0v48q-30 22-60 0z" fill="#F6B93B" stroke="#C98C2E" stroke-width="3"/><path d="M-30 -10h60M-30 6h60M-30 22h58" stroke="#C98C2E" stroke-width="2.5"/><ellipse cx="0" cy="14" rx="9" ry="8" fill="#5B3A1A"/><path d="M0 -38v10" stroke="#A0673E" stroke-width="4"/></g>';
  [[300, 70], [244, 104], [188, 130], [132, 150], [76, 166]].forEach(([x, y], i) => {
    s += bee(x, y, 0.95) + `<rect x="${x - 18}" y="${y + 18}" width="36" height="24" rx="8" fill="${TILE[i % TILE.length]}"/>` + ordinalText(x, y + 36, String(i + 1), ['st', 'nd', 'rd', 'th', 'th'][i], 15, '#fff');
  });
  s += flower(30, 226, C.pink) + flower(420, 228, C.violet) + flower(460, 222, C.yellow);
  return svg(480, 240, s, 'five bees flying in a line to their hive: 1st to 5th');
};
// cars on a winding road, each with a letter; some show their position, the rest are boxes to fill
function carRoad(spec) {
  const letters = spec.letters; const per = 5; const rows = Math.ceil(letters.length / per); const rowH = 92; const show = spec.show || {};
  let s = `<rect width="480" height="${rows * rowH + 16}" rx="16" fill="#BFEBDD"/>`;
  for (let r = 0; r < rows; r++) {
    const y = 24 + r * rowH + 44;
    s += `<rect x="20" y="${y - 14}" width="440" height="28" rx="14" fill="#fff"/><path d="M36 ${y}h408" stroke="#B2BAC6" stroke-width="2" stroke-dasharray="8 8"/>`;
    if (r < rows - 1) s += `<path d="M${r % 2 ? 34 : 446} ${y}v${rowH}" stroke="#fff" stroke-width="28" stroke-linecap="round"/>`;
  }
  letters.forEach((L, i) => {
    const r = Math.floor(i / per); const c = i % per; const col = r % 2 ? per - 1 - c : c;
    const x = 64 + col * 88; const y = 24 + r * rowH + 44;
    s += `<g transform="translate(${x} ${y})"><path d="M-30 6v-14q0-6 6-6h8l8-10h20l10 10h4q6 0 6 6v14z" fill="#FECA57" stroke="#E0A100" stroke-width="2"/><path d="M-12 -14l6-8h16l7 8z" fill="#D9F2FF"/>`
      + `<circle cx="-16" cy="8" r="6" fill="#2D3436"/><circle cx="18" cy="8" r="6" fill="#2D3436"/><circle cx="-16" cy="8" r="2.4" fill="#B2BAC6"/><circle cx="18" cy="8" r="2.4" fill="#B2BAC6"/>`
      + `<text x="2" y="4" text-anchor="middle" ${FONT} font-weight="800" font-size="16" fill="#2D3436">${esc(L)}</text></g>`;
    const label = show[L];
    if (label) { const [n, end] = splitOrdinal(label); s += `<rect x="${x - 20}" y="${y - 54}" width="40" height="26" rx="8" fill="#fff" stroke="${C.blue}" stroke-width="2"/>` + ordinalText(x, y - 34, n, end, 15, C.blue); }
    else s += `<rect x="${x - 20}" y="${y - 54}" width="40" height="26" rx="8" fill="#fff" stroke="#9AA4B1" stroke-width="2" stroke-dasharray="4 3"/>`;
  });
  return svg(480, rows * rowH + 16, s, `cars with the letters ${letters.join(' ')} in order`);
}
// a winners' podium: 2nd, 1st, 3rd, each child on their block
function podium(spec) {
  const at = { 1: [240, 110], 2: [120, 140], 3: [360, 160] }; let s = '<rect width="480" height="250" rx="16" fill="#FFF6E5"/>' + sparkle(60, 40, 1) + sparkle(420, 50, 0.9, C.pink) + sparkle(240, 24, 0.8, C.sky);
  for (const p of spec.places) {
    const [cx, top] = at[p.place] || [240, 110]; const col = { 1: '#FECA57', 2: '#C9D1DE', 3: '#F0B27A' }[p.place];
    s += `<rect x="${cx - 60}" y="${top}" width="120" height="${240 - top}" rx="8" fill="${col}"/><text x="${cx}" y="${top + 50}" text-anchor="middle" ${FONT} font-weight="800" font-size="40" fill="#fff">${p.place}</text>`
      + person(cx, top, { k: 0.62, top: TILE[p.place + 1], hair: p.hair || 'short', look: 'ahead', arm: p.place === 1 ? 'wave' : null, armSide: 1, armAngle: 20 });
    if (p.name) s += `<rect x="${cx - 40}" y="${top - 112}" width="80" height="24" rx="12" fill="#fff" stroke="${C.slate}" stroke-width="1.5"/><text x="${cx}" y="${top - 95}" text-anchor="middle" ${tfont(p.name)} font-weight="700" font-size="15" fill="${C.ink}">${esc(p.name)}</text>`;
  }
  return svg(480, 250, s, `a race podium: ${spec.places.map((p) => `${p.name || ''} ${p.place}`).join(', ')}`);
}
// a signboard on a post, its words as the lesson writes them
function signboard(x, y, text, w = 190) {
  const lines = wrap(text, isUr(text) ? 18 : 16).slice(0, 3); const h = 26 + lines.length * 34;
  let s = `<g transform="translate(${x} ${y})"><rect x="-6" y="${h - 6}" width="12" height="64" fill="#8D5A34"/><rect x="${-w / 2}" y="0" width="${w}" height="${h}" rx="10" fill="#C98C5E" stroke="#8D5A34" stroke-width="4"/>`
    + `<rect x="${-w / 2 + 8}" y="8" width="${w - 16}" height="${h - 16}" rx="6" fill="#FFF8E8"/>`;
  lines.forEach((l, i) => { s += `<text x="0" y="${42 + i * 34}" text-anchor="middle" ${tfont(l)} font-weight="700" font-size="20" fill="#B03A2E">${esc(l)}</text>`; });
  return `${s}</g>`;
}
function signboardVisual(spec) {
  const items = spec.items; const w = 480 / items.length; let s = '<rect width="480" height="190" rx="16" fill="#E8F7E4"/>' + meadow(150);
  items.forEach((t, i) => { s += signboard(r1(i * w + w / 2), 16, t, Math.min(200, w - 20)); });
  return svg(480, 190, s, `signboards: ${items.join(' · ')}`);
}
// a family in the park: the father, three children with flowers, the park's signboard
SCENES.park_family = (spec) => {
  let s = skyDefs('qsky5', '#B8E2FF', '#EEF8FF') + '<rect width="480" height="250" rx="16" fill="url(#qsky5)"/>' + sunFace(440, 40, 17) + cloud(220, 30, 0.7) + meadow(176);
  s += tree(60, 200, 0.95) + tree(420, 196, 0.8);
  s += signboard(370, 70, spec.sign || '', 170);
  s += person(150, 236, { k: 0.95, top: '#4A69BD', hair: 'short', moustache: HAIR, look: 'ahead', mouth: 'sad', arm: 'point', armSide: 1, armAngle: 70 })
    + person(222, 238, { k: 0.72, top: C.coral, hair: 'short', look: 'ahead', mouth: 'o' })
    + person(276, 238, { k: 0.68, top: '#8E5BC6', hair: 'scarf', scarf: '#F6E58D', look: 'ahead' })
    + person(320, 240, { k: 0.58, top: C.aqua, hair: 'scarf', scarf: '#FF8FB1', look: 'up' })
    + flower(246, 168, C.pink, 1.1) + flower(296, 172, C.yellow, 1) + flower(340, 180, C.violet, 1)
    + flower(110, 236, C.coral) + flower(380, 236, C.pink) + flower(440, 232, C.yellow) + butterfly(200, 120, C.orange, 0.8);
  return svg(480, 250, s, `a father and three children in a park; a signboard: ${spec.sign || ''}`);
};
// a road with a zebra crossing: two children cross holding hands; a traffic light, or none
SCENES.zebra_crossing = (spec) => {
  const signal = spec.signal !== false;
  let s = skyDefs('qsky6', '#B8E2FF', '#EEF8FF') + '<rect width="480" height="250" rx="16" fill="url(#qsky6)"/>' + sunFace(420, 40, 16) + cloud(220, 26, 0.6)
    + '<rect x="0" y="120" width="480" height="20" fill="#C9CDD8"/><rect x="0" y="140" width="480" height="84" fill="#5B6472"/><rect x="0" y="224" width="480" height="26" fill="#C9CDD8"/>'
    + '<path d="M0 182h120M360 182h120" stroke="#FECA57" stroke-width="4" stroke-dasharray="18 14"/>';
  for (let i = 0; i < 7; i++) s += `<rect x="${140 + i * 30}" y="144" width="18" height="76" rx="2" fill="#fff"/>`;
  // a car waiting, a school sign
  s += '<g transform="translate(406 160)"><rect x="-44" y="-26" width="88" height="34" rx="10" fill="#54A0FF"/><path d="M-26 -26l10-18h34l12 18z" fill="#54A0FF"/><path d="M-20 -26l7-12h12v12zM6 -26v-12h10l8 12z" fill="#D9F2FF"/><circle cx="-24" cy="10" r="9" fill="#2D3436"/><circle cx="24" cy="10" r="9" fill="#2D3436"/><circle cx="-44" cy="-12" r="4" fill="#FECA57"/></g>'
    + '<rect x="96" y="70" width="5" height="52" fill="#9AA4B1"/>' + roadSign('children', 98, 66, 20);
  if (signal) s += trafficLight(40, 30, 0.5, { faces: false });
  s += person(220, 214, { k: 0.66, top: C.coral, hair: 'short', look: 'ahead', arm: 'point', armSide: 1, armAngle: 100 })
    + person(262, 214, { k: 0.6, top: C.violet, hair: 'scarf', scarf: '#fff', look: 'ahead' });
  return svg(480, 250, s, signal ? 'two children cross the road at the zebra crossing; a traffic light' : 'a road with a zebra crossing and no traffic signal');
};

// ── THE HERO BADGE ───────────────────────────────────────────────────────────────────────
// A small round picture for the lesson's title card.
function heroBadge(spec) {
  if (!spec) return '';
  if (spec.type === 'clock') return `<svg class="qhero-art" viewBox="-6 -10 132 140" aria-hidden="true"><rect x="-6" y="-10" width="132" height="140" fill="#FFF3DC"/>${clockFace(60, 64, 46, spec.time)}</svg>`;
  if (spec.type === 'festivals') return festivalsBadge();
  if (spec.type === 'place_value') return placeValueBadge(spec);
  if (spec.type === 'greeting') return greeting(spec).replace('class="qart"', 'class="qhero-art" preserveAspectRatio="xMidYMid slice"').replace(/viewBox="[^"]*"/, 'viewBox="40 80 400 150"');
  if (spec.type === 'stairs') return stairs(spec).replace('class="qart"', 'class="qhero-art" preserveAspectRatio="xMidYMid slice"').replace(/viewBox="[^"]*"/, 'viewBox="60 30 360 180"');
  if (spec.type === 'solar_system') return solarSystem(spec).replace('class="qart"', 'class="qhero-art" preserveAspectRatio="xMidYMid slice"').replace(/viewBox="[^"]*"/, 'viewBox="130 40 220 170"');
  if (spec.type === 'traffic_light') return `<svg class="qhero-art" viewBox="-60 -14 120 120" aria-hidden="true"><rect x="-60" y="-14" width="120" height="120" fill="#E3F0FF"/>${trafficLight(0, -4, 0.82)}</svg>`;
  if (spec.type === 'scene') {
    const inner = scene(spec).replace(/^<svg[^>]*>/, '').replace(/<\/svg>$/, '');
    const box = { songbird: '140 20 200 200', lake: '90 20 260 220', kite_tree: '120 20 230 210', bee_line: '150 30 200 200', park_family: '110 60 190 190', zebra_crossing: '120 60 190 190' }[spec.scene] || '0 0 480 240';
    return `<svg class="qhero-art" viewBox="${box}" preserveAspectRatio="xMidYMid slice" aria-hidden="true">${inner}</svg>`;
  }
  return '';
}

// ── ICONS ─────────────────────────────────────────────────────────────────────────────────
// Small colourful icons for the page's labels and stage bars, drawn in a 24×24 box.
const ic = (body, cls = 'qic') => `<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true">${body}</svg>`;
const ICON = {
  key: () => ic('<circle cx="8" cy="9" r="5.5" fill="#FECA57" stroke="#E0A84B" stroke-width="1.5"/><circle cx="8" cy="9" r="2" fill="#fff"/><path d="M12 13l8.5 8.5M16.5 17.5l2.5-2.5M19 20l2.5-2.5" stroke="#E0A84B" stroke-width="2.8" stroke-linecap="round"/>'),
  tv: () => ic('<rect x="2" y="5" width="20" height="14" rx="4" fill="#FF6B6B"/><rect x="4.5" y="7.5" width="15" height="9" rx="2" fill="#FFF8E8"/><path d="M10 9.6v5l4.2-2.5z" fill="#FF6B6B"/><path d="M8 2.5l4 2.5 4-2.5" stroke="#FF6B6B" stroke-width="1.8" fill="none" stroke-linecap="round"/>'),
  clock: () => ic('<rect x="10" y="1" width="4" height="3" rx="1" fill="#FF6B6B"/><circle cx="12" cy="13.5" r="9" fill="#FF6B6B"/><circle cx="12" cy="13.5" r="6.8" fill="#fff"/><path d="M12 9.2v4.3l3 1.8" stroke="#303749" stroke-width="2" stroke-linecap="round" fill="none"/>'),
  mic: () => ic('<rect x="8.5" y="2" width="7" height="12.5" rx="3.5" fill="#FECA57"/><path fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" d="M5.5 11a6.5 6.5 0 0 0 13 0M12 17.5V21M8.5 21.5h7"/>'),
  chat: () => ic('<path fill="#1DD1A1" d="M12 2.8a9.2 9.2 0 0 0-8 13.7L2.8 21.2l4.8-1.2A9.2 9.2 0 1 0 12 2.8z"/><path fill="#fff" d="M8.6 7.4c.3-.3.8-.3 1 .1l1 1.9c.2.3.1.7-.2 1l-.6.6c.6 1.3 1.6 2.3 2.9 2.9l.6-.6c.3-.3.7-.4 1-.2l1.9 1c.4.2.4.7.1 1l-.9 1c-.6.6-1.6.7-2.4.3-2.2-1.1-3.9-2.8-5-5-.4-.8-.3-1.8.3-2.4l.8-.8z"/>'),
  reply: () => ic('<path fill="#54A0FF" d="M10 5 3 11.5l7 6.5v-4c5 0 8.5 1.5 11 5-1-5.5-4.5-10-11-11V5z"/>'),
  house: () => ic('<path fill="#FF6B6B" d="M12 2.5 1.5 11.5h3L12 5l7.5 6.5h3z"/><path fill="#FECA57" d="M4.5 11.5 12 5l7.5 6.5V21h-15z"/><rect x="10" y="14" width="4" height="7" rx="1" fill="#A0673E"/><rect x="6" y="12.5" width="3" height="3" rx=".6" fill="#54A0FF"/><rect x="15" y="12.5" width="3" height="3" rx=".6" fill="#54A0FF"/>'),
  bubble: () => ic('<path fill="#E3F0FF" stroke="#54A0FF" stroke-width="2" stroke-linejoin="round" d="M4 4h16a1.5 1.5 0 0 1 1.5 1.5v10A1.5 1.5 0 0 1 20 17h-9l-5 4v-4H4a1.5 1.5 0 0 1-1.5-1.5v-10A1.5 1.5 0 0 1 4 4z"/><circle cx="8" cy="10.5" r="1.4" fill="#54A0FF"/><circle cx="12" cy="10.5" r="1.4" fill="#54A0FF"/><circle cx="16" cy="10.5" r="1.4" fill="#54A0FF"/>'),
  star: () => ic('<path fill="#FECA57" stroke="#F2A20C" stroke-width="1.2" stroke-linejoin="round" d="M12 2.5l2.9 6 6.6.9-4.8 4.6 1.2 6.5L12 17.4l-5.9 3.1 1.2-6.5L2.5 9.4l6.6-.9z"/>'),
  help: () => ic('<circle cx="12" cy="12" r="10" fill="#54A0FF"/><path d="M9.2 9.2a2.9 2.9 0 1 1 4.2 2.6c-.9.5-1.4 1.1-1.4 2.1v.6" stroke="#fff" stroke-width="2.3" fill="none" stroke-linecap="round"/><circle cx="12" cy="17.6" r="1.4" fill="#fff"/>'),
  // section labels
  warmup: () => ic('<path d="M13 2 5 13.5h5.5L9 22l9-12.5h-5.5z" fill="#FECA57" stroke="#F2A20C" stroke-width="1.2" stroke-linejoin="round"/>'),
  setup: () => ic('<rect x="4" y="4" width="16" height="18" rx="2.5" fill="#FFF1D6" stroke="#FF9F43" stroke-width="1.8"/><rect x="8" y="2" width="8" height="4" rx="1.5" fill="#FF9F43"/><path d="M7.5 11l1.5 1.5 3-3M7.5 16.5l1.5 1.5 3-3" stroke="#1DD1A1" stroke-width="1.8" fill="none" stroke-linecap="round"/><path d="M13.5 11h3.5M13.5 16.5h3.5" stroke="#B2BAC6" stroke-width="1.8" stroke-linecap="round"/>'),
  question: () => ic('<path fill="#FECA57" d="M12 2.5a9 9 0 0 0-7.7 13.6L3 21l4.9-1.3A9 9 0 1 0 12 2.5z"/><path d="M9.5 9.3a2.6 2.6 0 1 1 3.8 2.3c-.8.4-1.3 1-1.3 1.8v.4" stroke="#7A4B00" stroke-width="2" fill="none" stroke-linecap="round"/><circle cx="12" cy="16.6" r="1.2" fill="#7A4B00"/>'),
  book: () => ic('<path d="M12 6.2C9.8 4.6 6.6 4.2 2.5 4.8v14c4.1-.6 7.3-.2 9.5 1.4z" fill="#FF8FB1"/><path d="M12 6.2c2.2-1.6 5.4-2 9.5-1.4v14c-4.1-.6-7.3-.2-9.5 1.4z" fill="#54A0FF"/><path d="M5 8.5c2-.3 3.7 0 5 .7M5 11.5c2-.3 3.7 0 5 .7M14 9.2c1.3-.7 3-1 5-.7M14 12.2c1.3-.7 3-1 5-.7" stroke="#fff" stroke-width="1.3" stroke-linecap="round"/>'),
  teach: () => ic('<rect x="2" y="3" width="15" height="11" rx="1.5" fill="#2F6F5E" stroke="#A0673E" stroke-width="1.5"/><path d="M5 7h6M5 10h4" stroke="#fff" stroke-width="1.4" stroke-linecap="round"/><circle cx="19" cy="9" r="2.6" fill="#E0A97E"/><path d="M15.5 21c0-4 1.5-8 3.5-8s3.5 4 3.5 8z" fill="#FF9F43"/><path d="M17 14l-4-3" stroke="#FF9F43" stroke-width="1.8" stroke-linecap="round"/>'),
  pencil: () => ic('<g transform="rotate(45 12 12)"><rect x="9" y="1.5" width="6" height="16" rx="1" fill="#FECA57"/><rect x="9" y="1.5" width="6" height="3.5" rx="1" fill="#FF8FB1"/><path d="M9 17.5h6l-3 5z" fill="#F1C27D"/><path d="M11 20.8h2l-1 1.7z" fill="#2D3436"/></g>'),
  warn: () => ic('<path fill="#FECA57" stroke="#F2A20C" stroke-width="1.4" stroke-linejoin="round" d="M12 2.5 1.8 20.5h20.4z"/><rect x="11" y="8.5" width="2" height="6.5" rx="1" fill="#7A4B00"/><circle cx="12" cy="17.6" r="1.25" fill="#7A4B00"/>'),
  group: () => ic('<circle cx="7.5" cy="8" r="3" fill="#E0A97E"/><circle cx="16.5" cy="8" r="3" fill="#C98C5E"/><path d="M2.5 20c0-4.5 2.2-7.5 5-7.5s5 3 5 7.5z" fill="#FF6B6B"/><path d="M11.5 20c0-4.5 2.2-7.5 5-7.5s5 3 5 7.5z" fill="#54A0FF"/><path d="M4.6 7c.5-2 1.6-2.8 2.9-2.8S10 5 10.4 7c-1-.8-1.8-1-2.9-1s-2 .2-2.9 1z" fill="#2B2521"/><path d="M13.6 7c.5-2 1.6-2.8 2.9-2.8S19 5 19.4 7c-1-.8-1.8-1-2.9-1s-2 .2-2.9 1z" fill="#2B2521"/>'),
  flag: () => ic('<path d="M5 22V3" stroke="#5B6472" stroke-width="2" stroke-linecap="round"/><path d="M5.8 3.5h13l-3 4 3 4h-13z" fill="#1DD1A1"/>'),
  ticket: () => ic('<path d="M3 6.5h18v3a2.5 2.5 0 0 0 0 5v3H3v-3a2.5 2.5 0 0 0 0-5z" fill="#A55EEA"/><path d="M15 6.5v11" stroke="#fff" stroke-width="1.4" stroke-dasharray="1.6 1.6"/><path d="M6.5 12l1.6 1.6 3-3.2" stroke="#fff" stroke-width="1.8" fill="none" stroke-linecap="round" stroke-linejoin="round"/>'),
  target: () => ic('<circle cx="12" cy="12" r="10" fill="#FF6B6B"/><circle cx="12" cy="12" r="7" fill="#fff"/><circle cx="12" cy="12" r="4" fill="#FF6B6B"/><circle cx="12" cy="12" r="1.6" fill="#fff"/><path d="M12 12l8-8M17 4h3v3" stroke="#303749" stroke-width="1.8" stroke-linecap="round" fill="none"/>'),
  steps: () => ic('<ellipse cx="7.5" cy="16" rx="3" ry="4.5" fill="#1DD1A1"/><ellipse cx="16.5" cy="8.5" rx="3" ry="4.5" fill="#1DD1A1"/><circle cx="6" cy="10" r="1.1" fill="#1DD1A1"/><circle cx="8" cy="9.4" r="1" fill="#1DD1A1"/><circle cx="15" cy="2.6" r="1.1" fill="#1DD1A1"/><circle cx="17" cy="2.1" r="1" fill="#1DD1A1"/>'),
  next: () => ic('<circle cx="12" cy="12" r="10" fill="#C9CDD8"/><path d="M9 7l5.5 5L9 17" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>'),
  sun: () => ic('<circle cx="12" cy="12" r="5" fill="#FECA57"/><path d="M12 2.5v2.5M12 19v2.5M2.5 12H5M19 12h2.5M5.3 5.3l1.8 1.8M16.9 16.9l1.8 1.8M5.3 18.7l1.8-1.8M16.9 7.1l1.8-1.8" stroke="#FECA57" stroke-width="2" stroke-linecap="round"/>'),
  board: () => ic('<rect x="2" y="3" width="20" height="14" rx="2" fill="#2F6F5E" stroke="#C98C5E" stroke-width="1.6"/><path d="M5.5 8h7M5.5 11.5h5" stroke="#fff" stroke-width="1.5" stroke-linecap="round"/><path d="M8 17l-2 4.5M16 17l2 4.5" stroke="#C98C5E" stroke-width="1.8" stroke-linecap="round"/><rect x="15" y="12" width="4" height="2" rx=".8" fill="#fff"/>'),
  bag: () => ic('<rect x="4" y="7" width="16" height="14.5" rx="4" fill="#54A0FF"/><path d="M8.5 7V5.5a3.5 3.5 0 0 1 7 0V7" stroke="#2E86DE" stroke-width="2" fill="none"/><rect x="7.5" y="13" width="9" height="5.5" rx="1.6" fill="#FECA57"/>'),
  bulb: () => ic('<path d="M12 2.5a6.5 6.5 0 0 0-3.8 11.8c.7.5 1.1 1.3 1.1 2.2v.5h5.4v-.5c0-.9.4-1.7 1.1-2.2A6.5 6.5 0 0 0 12 2.5z" fill="#FECA57"/><rect x="9.3" y="18" width="5.4" height="1.8" rx=".7" fill="#B2BAC6"/><rect x="10" y="20.4" width="4" height="1.6" rx=".7" fill="#B2BAC6"/><path d="M10.3 9.5l1.7 2 1.7-2" stroke="#F2A20C" stroke-width="1.4" fill="none"/>'),
  clipboard: () => ic('<rect x="4" y="4" width="16" height="18" rx="2.5" fill="#fff" stroke="#FECA57" stroke-width="1.8"/><rect x="8" y="2" width="8" height="4" rx="1.5" fill="#FECA57"/><path d="M7.5 11l1.5 1.5 3-3M7.5 16.5l1.5 1.5 3-3" stroke="#1DD1A1" stroke-width="1.8" fill="none" stroke-linecap="round"/><path d="M13.5 11h3.5M13.5 16.5h3.5" stroke="#C9D4E6" stroke-width="1.8" stroke-linecap="round"/>'),
  check: () => ic('<circle cx="12" cy="12" r="10" fill="#1DD1A1"/><path d="M7 12.4l3.3 3.3L17 9" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>'),
};
// the stage bars' badges: a white disc with the stage's own picture
const STAGE_ICON = {
  opening: () => ICON.sun(), explanation: () => ic('<path d="M12 2.5a6.5 6.5 0 0 0-3.8 11.8c.7.5 1.1 1.3 1.1 2.2v.5h5.4v-.5c0-.9.4-1.7 1.1-2.2A6.5 6.5 0 0 0 12 2.5z" fill="#FECA57"/><rect x="9.3" y="18" width="5.4" height="1.8" rx=".7" fill="#B2BAC6"/><rect x="10" y="20.4" width="4" height="1.6" rx=".7" fill="#B2BAC6"/><path d="M10.3 9.5l1.7 2 1.7-2" stroke="#F2A20C" stroke-width="1.4" fill="none"/>'),
  we_do: () => ICON.group(), you_do: () => ICON.pencil(), check: () => ICON.check(), homework: () => ICON.house(),
};
const stageIcon = (id) => (STAGE_ICON[id] ? STAGE_ICON[id]() : '');

// a face for a speaker in the read-aloud lines: a kind of face (girl in a headscarf, cheeky boy,
// a man in a cap …) from the lesson's speakers list, otherwise one colour per speaker in turn
const FACE_TOPS = ['#8E5BC6', '#2E86DE', '#FF9F43', '#16A085', '#FF6B6B'];
const FACE_KIND = {
  girl_scarf: { hair: 'scarf', scarf: C.pink, top: '#8E5BC6' }, girl: { hair: 'long', top: C.pink }, boy: { hair: 'short', top: C.skyD },
  boy_cheeky: { hair: 'short', top: C.orange, mouth: 'grin' }, man_cap: { hair: 'cap', cap: C.green, top: '#6C7A89', beard: '#3B2F2F' },
  man_moustache: { hair: 'short', top: '#4A69BD', moustache: HAIR }, elder: { hair: 'grey', beard: '#E3E6EC', top: '#6C7A89' },
  woman: { hair: 'scarf', scarf: C.violet, top: '#16A085' },
};
function face(i, kind) {
  const o = FACE_KIND[kind] || { hair: 'short', top: FACE_TOPS[i % FACE_TOPS.length] };
  const bg = ['#FFE3E3', '#E3F0FF', '#FFF1D6', '#DDF7EC', '#EFE3FF'][i % 5];
  return `<svg class="qface" viewBox="-36 -142 72 72" aria-hidden="true"><circle cx="0" cy="-106" r="36" fill="${bg}"/>${person(0, 0, { ...o, k: 1 })}</svg>`;
}

// the good-citizen chart's small pictures (primary.js lays out the chart, with the lesson's words)
const DEED = {
  fan_bulb: () => ic('<circle cx="8" cy="8" r="2" fill="#5B6472"/><path d="M8 8c-1-4 0-6 2-6s1 4-2 6zM8 8c4-1 6 0 6 2s-4 1-6-2zM8 8c1 4 0 6-2 6s-1-4 2-6zM8 8c-4 1-6 0-6-2s4-1 6 2z" fill="#54A0FF"/><path d="M17 4a4 4 0 0 0-2.4 7.2c.4.3.6.8.6 1.3v.5h3.6v-.5c0-.5.2-1 .6-1.3A4 4 0 0 0 17 4z" fill="#FECA57"/><rect x="15.3" y="14.2" width="3.4" height="1.4" rx=".6" fill="#B2BAC6"/><path d="M3 21l18-18" stroke="#E53935" stroke-width="2.2" stroke-linecap="round"/>'),
  tap: () => ic('<path d="M4 7h9a3 3 0 0 1 3 3v3h-4v-2H4z" fill="#9AA4B1"/><rect x="7" y="3" width="3" height="4" fill="#5B6472"/><rect x="5" y="2" width="7" height="2" rx="1" fill="#E53935"/><path d="M14 16c0 2-1.5 3.5-1.5 4.5a1.5 1.5 0 0 0 3 0c0-1-1.5-2.5-1.5-4.5z" fill="#54A0FF" opacity=".35"/><path d="M18 14l4 4" stroke="#1DD1A1" stroke-width="2.2" stroke-linecap="round"/>'),
  dustbin: () => ic('<rect x="5" y="8" width="14" height="14" rx="2" fill="#1DD1A1"/><rect x="3.5" y="5.5" width="17" height="3" rx="1.5" fill="#16A085"/><rect x="10" y="3.5" width="4" height="2.5" rx="1" fill="#16A085"/><path d="M9 11v8M12 11v8M15 11v8" stroke="#fff" stroke-width="1.5" stroke-linecap="round"/><path d="M15 2.5l3 2-1 1.5" fill="#FECA57"/>'),
  queue: () => ic('<circle cx="5" cy="7" r="2.3" fill="#E0A97E"/><circle cx="12" cy="7" r="2.3" fill="#C98C5E"/><circle cx="19" cy="7" r="2.3" fill="#E0A97E"/><path d="M2 20c0-5 1.5-9 3-9s3 4 3 9z" fill="#FF6B6B"/><path d="M9 20c0-5 1.5-9 3-9s3 4 3 9z" fill="#54A0FF"/><path d="M16 20c0-5 1.5-9 3-9s3 4 3 9z" fill="#1DD1A1"/>'),
  plant: () => ic('<path d="M7 15h10l-1.5 7h-7z" fill="#E67E22"/><path d="M12 15V9" stroke="#2ECC71" stroke-width="2"/><path d="M12 10c-4 0-6-2-6-5 3 0 6 1 6 5zM12 9c0-4 2-6 6-6 0 3-2 6-6 6z" fill="#2ECC71"/><path d="M17.5 12.5c1-1.2 3-.6 3 1 0 1.7-3 3.5-3 3.5s-3-1.8-3-3.5c0-1.6 2-2.2 3-1z" fill="#FF6B6B"/>'),
  ticket: () => ic('<path d="M3 6.5h18v3a2.5 2.5 0 0 0 0 5v3H3v-3a2.5 2.5 0 0 0 0-5z" fill="#FECA57"/><path d="M15 6.5v11" stroke="#fff" stroke-width="1.4" stroke-dasharray="1.6 1.6"/><rect x="5.5" y="10" width="7" height="1.6" rx=".8" fill="#A0673E"/><rect x="5.5" y="13" width="5" height="1.6" rx=".8" fill="#A0673E"/>'),
  heart: () => ic('<path d="M12 21s-8-5.2-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 10c0 5.8-8 11-8 11z" fill="#FF6B6B"/><path d="M12 9.5l1 2 2.2.3-1.6 1.5.4 2.2-2-1-2 1 .4-2.2-1.6-1.5 2.2-.3z" fill="#fff"/>'),
};

// THE SOLAR SYSTEM, as a board sketch: the Sun at the centre, eight orbits (unlabelled, as the
// board says), a planet on each (small rocky ones near the Sun, big gas ones farther out), the
// asteroid belt between the fourth and fifth orbits, and one comet with its tail pointing away
// from the Sun. No names are written on it: the lesson's board leaves the labels to the class.
function solarSystem(spec) {
  const W = 480; const H = 250; const cx = 240; const cy = 125;
  const rx = [44, 62, 80, 98, 140, 168, 194, 218]; const k = 0.43;
  const planet = [
    { r: 4.5, c: '#B8B2A8' }, { r: 6.5, c: '#F2C27B' }, { r: 7, c: '#4FA3E0', land: '#4CC37A' }, { r: 5.5, c: '#E2683C' },
    { r: 13, c: '#E8A15B', bands: '#C97B3A' }, { r: 11, c: '#F1D08A', ring: true }, { r: 8.5, c: '#8FE0E8' }, { r: 8.5, c: '#4C6FE6' },
  ];
  const ang = [200, 320, 70, 160, 300, 30, 230, 120];
  let s = `<rect width="${W}" height="${H}" rx="14" fill="#1B2140"/>`;
  // a few stars
  [[24, 30], [70, 210], [120, 22], [380, 26], [450, 200], [430, 70], [40, 120], [300, 230], [200, 18], [460, 130]].forEach(([x, y], i) => { s += `<circle cx="${x}" cy="${y}" r="${i % 3 ? 1.2 : 1.8}" fill="#fff" opacity=".8"/>`; });
  rx.forEach((r) => { s += `<ellipse cx="${cx}" cy="${cy}" rx="${r}" ry="${r1(r * k)}" fill="none" stroke="#7F8BC4" stroke-width="1.2" stroke-dasharray="${r > 100 ? '4 4' : '3 3'}"/>`; });
  // the asteroid belt between the 4th and 5th orbits
  for (let i = 0; i < 46; i++) {
    const a = (i / 46) * Math.PI * 2; const rr = 112 + ((i * 37) % 13);
    s += `<circle cx="${r1(cx + Math.cos(a) * rr)}" cy="${r1(cy + Math.sin(a) * rr * k)}" r="${(i % 3) + 1}" fill="#A0673E" opacity=".9"/>`;
  }
  // the Sun, smiling
  s += `<circle cx="${cx}" cy="${cy}" r="30" fill="#FECA57" opacity=".25"/><circle cx="${cx}" cy="${cy}" r="21" fill="#FECA57" stroke="#F2A20C" stroke-width="2"/>`
    + `<circle cx="${cx - 7}" cy="${cy - 4}" r="2.2" fill="#7A4B00"/><circle cx="${cx + 7}" cy="${cy - 4}" r="2.2" fill="#7A4B00"/><path d="M${cx - 8} ${cy + 5}q8 7 16 0" stroke="#7A4B00" stroke-width="2.2" fill="none" stroke-linecap="round"/>`;
  rx.forEach((r, i) => {
    const a = (ang[i] * Math.PI) / 180; const x = r1(cx + Math.cos(a) * r); const y = r1(cy + Math.sin(a) * r * k); const p = planet[i];
    if (p.ring) s += `<ellipse cx="${x}" cy="${y}" rx="${r1(p.r * 1.9)}" ry="${r1(p.r * 0.55)}" fill="none" stroke="#D9B26A" stroke-width="2.4"/>`;
    s += `<circle cx="${x}" cy="${y}" r="${p.r}" fill="${p.c}"/>`;
    if (p.bands) s += `<path d="M${r1(x - p.r * 0.9)} ${r1(y - 3)}h${r1(p.r * 1.8)}M${r1(x - p.r * 0.95)} ${r1(y + 3)}h${r1(p.r * 1.9)}" stroke="${p.bands}" stroke-width="2"/>`;
    if (p.land) s += `<path d="M${r1(x - 3)} ${r1(y - 2)}q2 -3 4 0q1 3 -2 3z" fill="${p.land}"/>`;
  });
  // a comet, its tail pointing away from the Sun
  s += `<path d="M408 52 L470 18 L474 30 Z" fill="#BFE6FF" opacity=".55"/><path d="M408 52 L462 28" stroke="#E3F4FF" stroke-width="3" stroke-linecap="round" opacity=".8"/><circle cx="408" cy="52" r="6" fill="#E3F4FF" stroke="#8FD0FF" stroke-width="1.6"/>`;
  return svg(W, H, s, 'the solar system: the Sun, eight orbits, the asteroid belt and a comet');
}

// THE THREE STAIRS of a self-introduction (or any ordered steps a lesson names): a staircase, one
// step per item in reading order with its number and the lesson's own word, a child at the foot.
function stairs(spec) {
  const steps = spec.steps || []; const n = steps.length; const rtl = !!spec.rtl;
  const W = 480; const H = 210; const sw = 120; const sh = 46; const x0 = 70;
  let s = `<rect width="${W}" height="${H}" rx="14" fill="#EAF6FF"/><rect y="${H - 22}" width="${W}" height="22" fill="#CDEFD9"/>`;
  steps.forEach((t, i) => {
    const xi = rtl ? W - x0 - (i + 1) * sw : x0 + i * sw; const top = H - 22 - (i + 1) * sh;
    s += `<rect x="${xi}" y="${top}" width="${sw}" height="${(i + 1) * sh}" rx="8" fill="${TILE[i % TILE.length]}"/>`
      + `<circle cx="${xi + 22}" cy="${top + 22}" r="14" fill="#fff"/><text x="${xi + 22}" y="${top + 28}" text-anchor="middle" ${FONT} font-weight="800" font-size="16" fill="${C.ink}">${esc(String(t.n || i + 1))}</text>`
      + `<text x="${xi + 72}" y="${top + 30}" text-anchor="middle" ${FONT} font-weight="700" font-size="${/[؀-ۿ]/.test(t.word) ? 20 : 17}" fill="#fff">${esc(t.word)}</text>`;
  });
  // a child at the foot of the stairs, ready to climb
  const cx = rtl ? W - 32 : 32;
  s += `<g transform="translate(${cx} ${H - 22})"><path d="M-12 0c1-16 5-24 12-24s11 8 12 24z" fill="${C.sky}"/><circle cx="0" cy="-34" r="11" fill="${SKIN}"/>`
    + `<path d="M-11 -36c-1-8 4-12 11-12s12 4 11 12c-2-4-6-6-11-6s-9 2-11 6z" fill="${HAIR}"/><circle cx="-4" cy="-34" r="1.5" fill="${HAIR}"/><circle cx="4" cy="-34" r="1.5" fill="${HAIR}"/>`
    + `<path d="M-4 -29c2.5 2 5.5 2 8 0" stroke="#8A2E2E" stroke-width="1.6" fill="none" stroke-linecap="round"/></g>`;
  return svg(W, H, s, steps.map((t) => t.word).join(' → '));
}

// A GREETING, as the lesson's board states it: the child who is walking greets first, the child who
// is standing replies in full. Two ordinary children (never a revered figure); the words in the two
// bubbles are the lesson's own board lines.
function greeting(spec) {
  const W = 480; const H = 250; const ur = (t) => /[؀-ۿ]/.test(String(t));
  const bubble = (x, y, w, text, tail) => `<g><rect x="${x}" y="${y}" width="${w}" height="54" rx="16" fill="#fff" stroke="${C.sky}" stroke-width="2.4"/>`
    + `<path d="M${tail} ${y + 54}l10 16 7-16z" fill="#fff" stroke="${C.sky}" stroke-width="2.4" stroke-linejoin="round"/><rect x="${tail - 1}" y="${y + 50}" width="19" height="6" fill="#fff"/>`
    + `<text x="${x + w / 2}" y="${y + 35}" text-anchor="middle" ${FONT} ${ur(text) ? 'direction="rtl"' : ''} font-size="18" fill="${C.ink}">${esc(text)}</text></g>`;
  let s = `<rect width="${W}" height="${H}" rx="14" fill="#EAF6FF"/><rect y="${H - 34}" width="${W}" height="34" fill="#CDEFD9"/>`;
  // the walking child (on the right, moving left) and the standing child (on the left)
  const child = (x, top, scarf, walking) => `<g transform="translate(${x} ${H - 34}) scale(1.45)">`
    + `<path d="M-15 0c1-22 6-32 15-32s14 10 15 32z" fill="${top}"/>`
    + (walking ? '<path d="M-6 0l-9 14M6 0l10 13" stroke="#5B6472" stroke-width="5" stroke-linecap="round"/><path d="M22 -20h12M24 -12h10M22 -4h12" stroke="#9AA4B1" stroke-width="2.4" stroke-linecap="round"/>' : '<path d="M-6 0v14M6 0v14" stroke="#5B6472" stroke-width="5" stroke-linecap="round"/>')
    + (scarf ? `<path d="M-16 -44c0-14 7-21 16-21s16 7 16 21c0 7-2 12-6 15h-20c-4-3-6-8-6-15z" fill="${scarf}"/>` : '')
    + `<circle cx="0" cy="-45" r="${scarf ? 11 : 13}" fill="${SKIN}"/>`
    + (scarf ? '' : `<path d="M-13 -48c-1-9 5-14 13-14s14 5 13 14c-3-5-7-7-13-7s-10 2-13 7z" fill="${HAIR}"/>`)
    + `<circle cx="-4" cy="-45" r="1.6" fill="${HAIR}"/><circle cx="4" cy="-45" r="1.6" fill="${HAIR}"/><path d="M-4 -39c2.5 2 5.5 2 8 0" stroke="#8A2E2E" stroke-width="1.6" fill="none" stroke-linecap="round"/>`
    + (top === C.coral ? '<path d="M14 -24q14 -10 12 -24" stroke="#E0A97E" stroke-width="5" fill="none" stroke-linecap="round"/>' : '') + '</g>';
  s += child(372, C.coral, null, true) + child(108, C.aqua, C.violet, false);
  const [first, reply] = spec.lines || [];
  s += bubble(212, 12, 258, first, 380) + bubble(10, 78, 290, reply, 100);
  return svg(W, H, s, [first, reply].filter(Boolean).join(' / '));
}
// TWO FESTIVALS ON THE BOARD, as a lesson's hook states it: the teacher draws two circles on the
// board and writes a festival in each (the lesson's own words). Eid is a crescent over a mosque, the
// national day the flag of Pakistan. No person is drawn.
const BOARD = '#2F4A3F';
const starPath = (cx, cy, r) => `M${Array.from({ length: 10 }, (_, k) => {
  const a = -Math.PI / 2 + (k * Math.PI) / 5; const q = k % 2 ? r * 0.42 : r;
  return `${r1(cx + q * Math.cos(a))} ${r1(cy + q * Math.sin(a))}`;
}).join('L')}z`;
const eidIcon = (bg) => `<circle cx="24" cy="-44" r="13" fill="${C.yellow}"/><circle cx="30" cy="-49" r="11" fill="${bg}"/>`
  + `<path d="${starPath(-20, -46, 6)}" fill="${C.yellow}"/>`
  + `<rect x="-41" y="-24" width="8" height="46" fill="#DEF4E7"/><path d="M-41 -24l4-11 4 11z" fill="#DEF4E7"/>`
  + `<rect x="33" y="-24" width="8" height="46" fill="#DEF4E7"/><path d="M33 -24l4-11 4 11z" fill="#DEF4E7"/>`
  + `<path d="M-20 -2a20 20 0 0 1 40 0z" fill="#DEF4E7"/><path d="M0 -22v-9" stroke="#DEF4E7" stroke-width="2.4" stroke-linecap="round"/>`
  + `<rect x="-28" y="-3" width="56" height="25" rx="2" fill="#DEF4E7"/><path d="M-6 22v-12a6 6 0 0 1 12 0v12z" fill="${bg}"/>`;
const flagIcon = () => `<rect x="-40" y="-50" width="4.5" height="74" rx="2" fill="#D9DEE5"/><circle cx="-37.7" cy="-52" r="4" fill="${C.yellow}"/>`
  + '<rect x="-35.5" y="-47" width="18" height="46" fill="#fff"/><rect x="-17.5" y="-47" width="58" height="46" fill="#01411C"/>'
  + '<circle cx="10" cy="-23" r="13" fill="#fff"/><circle cx="14.5" cy="-27.5" r="11" fill="#01411C"/>'
  + `<path d="${starPath(19, -31, 5.5)}" fill="#fff" transform="rotate(-35 19 -31)"/>`;
function festivals(spec) {
  const W = 480; const H = 220; const [a, b] = spec.circles || []; const rtl = spec.rtl !== false;
  const circle = (cx, label, icon) => `<circle cx="${cx}" cy="106" r="86" fill="none" stroke="#F4F1E6" stroke-width="3.5" opacity=".9"/>`
    + `<g transform="translate(${cx} 108)">${icon}</g>`
    + `<text x="${cx}" y="168" text-anchor="middle" ${FONT} ${/[؀-ۿ]/.test(String(label)) ? 'direction="rtl" ' : ''}font-size="21" font-weight="700" fill="#F4F1E6">${esc(label)}</text>`;
  let s = `<rect width="${W}" height="${H}" rx="14" fill="#8A5A36"/><rect x="9" y="9" width="${W - 18}" height="${H - 18}" rx="8" fill="${BOARD}"/>`;
  const [x1, x2] = rtl ? [350, 130] : [130, 350];
  s += circle(x1, a, eidIcon(BOARD)) + circle(x2, b, flagIcon());
  return svg(W, H, s, [a, b].filter(Boolean).join(' · '));
}
// the badge on the title card: the two festivals' pictures side by side, without their words
function festivalsBadge() {
  return `<svg class="qhero-art" viewBox="0 0 120 120" aria-hidden="true"><rect width="120" height="120" fill="${BOARD}"/>`
    + `<g transform="translate(84 72) scale(.62)">${eidIcon(BOARD)}</g><g transform="translate(36 70) scale(.62)">${flagIcon()}</g></svg>`;
}
// PLACE VALUE, as a maths lesson builds it: one column per place, holding exactly as many pieces as
// that digit says — base-10 blocks (cube 1000 · flat 100 · rod 10 · dot 1) or bundles of sticks
// (hundred-bundle · bundle of ten · single stick). Counted from the lesson's own number, never from
// a picture description, so the drawing cannot disagree with the sum beside it.
const WOOD = '#D9A066'; const WOOD_D = '#A0673E';
const PV_PIECE = {
  cube: { w: 30, h: 30, col: C.violet, draw: (x, y) => `<path d="M${x} ${y + 8}h22v22h-22z" fill="#C49BF2" stroke="#7B3FC4" stroke-width="1.4"/><path d="M${x} ${y + 8}l8-8h22l-8 8z" fill="#DCC3F8" stroke="#7B3FC4" stroke-width="1.4"/><path d="M${x + 22} ${y + 8}l8-8v22l-8 8z" fill="#A66EE6" stroke="#7B3FC4" stroke-width="1.4"/>` },
  flat: { w: 30, h: 30, col: C.orange, draw: (x, y) => `<rect x="${x}" y="${y}" width="30" height="30" fill="#FFD2A6" stroke="#E07B1A" stroke-width="1.4"/>${Array.from({ length: 9 }, (_, k) => `<path d="M${x + 3 * (k + 1)} ${y}v30M${x} ${y + 3 * (k + 1)}h30" stroke="#F0A35E" stroke-width=".6"/>`).join('')}` },
  rod: { w: 9, h: 46, col: C.sky, draw: (x, y) => `<rect x="${x}" y="${y}" width="9" height="46" fill="#BFDDFF" stroke="#2E86DE" stroke-width="1.3"/>${Array.from({ length: 9 }, (_, k) => `<path d="M${x} ${r1(y + 4.6 * (k + 1))}h9" stroke="#7DB7F5" stroke-width=".7"/>`).join('')}` },
  dot: { w: 14, h: 14, col: C.coral, draw: (x, y) => `<circle cx="${x + 7}" cy="${y + 7}" r="6" fill="${C.coral}"/>` },
  bigbundle: { w: 30, h: 56, col: C.orange, draw: (x, y) => `${Array.from({ length: 7 }, (_, k) => `<rect x="${x + k * 4.2}" y="${y}" width="3.4" height="56" rx="1.2" fill="${k % 2 ? WOOD : '#E2B07C'}" stroke="${WOOD_D}" stroke-width=".5"/>`).join('')}<rect x="${x - 1}" y="${y + 13}" width="32" height="5" rx="2" fill="${C.coral}"/><rect x="${x - 1}" y="${y + 38}" width="32" height="5" rx="2" fill="${C.coral}"/>` },
  bundle: { w: 16, h: 56, col: C.sky, draw: (x, y) => `${Array.from({ length: 5 }, (_, k) => `<rect x="${x + k * 3.2}" y="${y}" width="2.6" height="56" rx="1" fill="${k % 2 ? WOOD : '#E2B07C'}" stroke="${WOOD_D}" stroke-width=".4"/>`).join('')}<rect x="${x - 1}" y="${y + 25}" width="18" height="5" rx="2" fill="${C.coral}"/>` },
  stick: { w: 5, h: 56, col: C.aqua, draw: (x, y) => `<rect x="${x}" y="${y}" width="4" height="56" rx="1.4" fill="${WOOD}" stroke="${WOOD_D}" stroke-width=".6"/>` },
};
const PV_KIND = { blocks: ['cube', 'flat', 'rod', 'dot'], sticks: [null, 'bigbundle', 'bundle', 'stick'] };
function placeValue(spec) {
  const heads = spec.heads || [];
  const n = heads.length;
  const digits = String(spec.number).padStart(n, ' ').slice(-n).split('');
  const pieces = PV_KIND[spec.kind === 'sticks' ? 'sticks' : 'blocks'].slice(-n);
  const W = 480; const colW = (W - 16) / n; const top = 34;
  const cols = digits.map((d, i) => {
    const piece = PV_PIECE[pieces[i]] || PV_PIECE.dot;
    const count = /\d/.test(d) ? Number(d) : 0;
    const perRow = Math.max(1, Math.floor((colW - 14) / (piece.w + 5)));
    const rows = Math.ceil(count / perRow);
    return { d, piece, count, perRow, rows, h: rows ? rows * (piece.h + 6) - 6 : 0 };
  });
  const areaH = Math.max(40, ...cols.map((c) => c.h));
  const H = top + 12 + areaH + 58;
  let s = `<rect width="${W}" height="${H}" rx="14" fill="#F7FAFF"/>`;
  cols.forEach((c, i) => {
    const x0 = 8 + i * colW;
    s += `<rect x="${x0 + 3}" y="6" width="${colW - 6}" height="${H - 12}" rx="10" fill="#fff" stroke="#DFE3EA" stroke-width="1.5"/>`
      + `<rect x="${x0 + 3}" y="6" width="${colW - 6}" height="26" rx="10" fill="${c.piece.col}"/><rect x="${x0 + 3}" y="22" width="${colW - 6}" height="10" fill="${c.piece.col}"/>`
      + `<text x="${x0 + colW / 2}" y="24" text-anchor="middle" ${FONT} font-weight="800" font-size="14" fill="#fff">${esc(heads[i])}</text>`;
    const rowW = Math.min(c.count, c.perRow) * (c.piece.w + 5) - 5;
    for (let k = 0; k < c.count; k++) {
      const col = k % c.perRow; const row = Math.floor(k / c.perRow);
      const px = x0 + (colW - rowW) / 2 + col * (c.piece.w + 5);
      const py = top + 12 + (areaH - c.h) / 2 + row * (c.piece.h + 6);
      s += c.piece.draw(r1(px), r1(py));
    }
    s += `<text x="${x0 + colW / 2}" y="${H - 18}" text-anchor="middle" ${FONT} font-weight="800" font-size="30" fill="${C.ink}">${esc(c.d.trim())}</text>`;
  });
  return svg(W, H, s, `${spec.number}: ${heads.map((h, i) => `${digits[i].trim() || 0} ${h}`).join(', ')}`);
}
function placeValueBadge(spec) {
  const kinds = spec.kind === 'sticks' ? ['bigbundle', 'bundle', 'stick'] : ['cube', 'flat', 'rod', 'dot'];
  const xs = spec.kind === 'sticks' ? [22, 60, 84] : [14, 48, 84, 98];
  return `<svg class="qhero-art" viewBox="0 0 120 120" aria-hidden="true"><rect width="120" height="120" fill="#F7FAFF"/>${kinds.map((k, i) => PV_PIECE[k].draw(xs[i], 60 - PV_PIECE[k].h / 2)).join('')}</svg>`;
}
// the pieces as small inline icons, for a line that names them ("[cube] = 1000")
const PV_ICON = (name) => {
  const p = PV_PIECE[name === 'stick' ? 'stick' : name];
  if (!p) return '';
  const k = 18 / Math.max(p.w, p.h);
  return `<svg class="qpv" viewBox="-2 -2 ${p.w + 4} ${p.h + 4}" width="${r1((p.w + 4) * k)}" height="${r1((p.h + 4) * k)}" aria-label="${name}" role="img">${p.draw(0, 0)}</svg>`;
};
const DRAW = {
  clock, clock_pair: clockPair, tiles, blender, blender_list: blenderList, blend_steps: blendSteps, scene, predict, dictionary, poster,
  traffic_light: trafficLightVisual, road_signs: roadSigns, road_sign: roadSignOne, look_steps: lookSteps, ordinal_row: ordinalRow,
  car_road: carRoad, podium, signboards: signboardVisual, solar_system: solarSystem, stairs, greeting, festivals,
  place_value: placeValue,
};
// the visual types drawn as HTML by primary.js rather than as SVG here
const HTML_VISUALS = ['story_map', 'tracker', 'deeds', 'compare', 'flow'];
function draw(spec) {
  if (!spec || !spec.type) return '';
  const f = DRAW[spec.type];
  if (!f) throw new Error(`no drawing for visual type "${spec.type}"`);
  return f(spec);
}

module.exports = { draw, DRAW, HTML_VISUALS, heroBadge, ICON, DEED, stageIcon, face, parseTime, C, PV_ICON };
